"""Frozen hero-name label vocabulary for HeroMaskedFromDeckMetric (and
the hero positions of HeroConditionedInclusionMetric).

FRESHNESS: generated by published_decklists.count_decks_per_hero() over
data/final/decks/flesh_and_blood.db + data/final/cards/flesh_and_blood.jsonl
on 2026-10-01. 4,152 published decklists have exactly one hero, over
125 distinct heroes (188 decks down to 1). CUTOFF: a hero with at least
MIN_DECKS_PER_HERO = 20 decks gets its own label (48 heroes, 3,698
decks, 89%); the other 77 heroes (454 decks) share OTHER_LABEL - below
20 decks a class would be little more than noise in an 8/1/1 split.
Names are the binder's card names (a two-faced hero keeps its
"Front // Back" name). A new set's heroes stay OTHER until this tuple is
regenerated and diffed.
"""

MIN_DECKS_PER_HERO = 20

HERO_NAMES: tuple[str, ...] = (
    "Arakni, 5L!p3d 7hRu 7h3 cR4X",
    "Arakni, Marionette",
    "Aurora, Shooting Star",
    "Azalea, Ace in the Hole",
    "Bravo, Showstopper",
    "Bravo, Star of the Show",
    "Briar",
    "Briar, Warden of Thorns",
    "Chane // Chane",
    "Chane, Bound by Shadow",
    "Cindra, Dracai of Retribution",
    "Dash I/O // Dash I/O",
    "Dash, Inventor Extraordinaire",
    "Dorinthea Ironsong",
    "Dromai, Ash Artist",
    "Enigma, Ledger of Ancestry",
    "Fai, Rising Rebellion",
    "Fang, Dracai of Blades",
    "Florian",
    "Florian, Rotwood Harbinger",
    "Gravy Bones, Shipwrecked Looter",
    "Ira, Crimson Haze",
    "Ira, Scarlet Revenger",
    "Iyslander",
    "Jarl Vetreiði",
    "Kano, Dracai of Aether",
    "Kassai of the Golden Sand",
    "Kassai, Cintari Sellsword // Kassai, Cintari Sellsword",
    "Katsu, the Wanderer",
    "Kayo",
    "Kayo, Armed and Dangerous",
    "Levia, Shadowborn Abomination // Levia, Shadowborn Abomination",
    "Lexi, Livewire",
    "Nuu, Alluring Desire",
    "Oldhim // Oldhim",
    "Oldhim, Grandfather of Eternity",
    "Oscilio",
    "Oscilio, Constella Intelligence",
    "Prism, Awakener of Sol",
    "Prism, Sculptor of Arc Light",
    "Rhinar, Reckless Rampage",
    "Ser Boltyn, Breaker of Dawn // Ser Boltyn, Breaker of Dawn",
    "Uzuri, Switchblade",
    "Verdance, Thorn of the Rose",
    "Victor Goldmane, High and Mighty",
    "Viserai, Rune Blood",
    "Vynnset, Iron Maiden // Vynnset, Iron Maiden",
    "Zen, Tamer of Purpose",
)
