"""A static snapshot of every (data_type, expansion, format_code) triple
17Lands has actually published a file for, as of 2026-09-06.

Third way to produce SeventeenLandsFileRefs, alongside the two
described in refs.py's module docstring. Exists because validity here
isn't systematic — e.g. STX+Sealed only ever got a GAME file, never
DRAFT or REPLAY — so neither "try the full cartesian product of every
enum value" nor a runtime fetch can derive it:
https://www.17lands.com/public_datasets is a client-rendered SPA (its
table is populated by JS after load), so a plain GET returns an empty
shell with no links in it — LandingPageParser can't be pointed at the
live URL directly. This table was produced by saving that page's
fully-rendered HTML (from a real browser) to disk and running
LandingPageParser against the saved file once, by hand.

To refresh: open https://www.17lands.com/public_datasets in a browser,
save the fully-rendered page HTML, then re-run LandingPageParser().parse()
against it and regenerate _KNOWN_VALID_TRIPLES below. There's no way to
automate that refresh from within this codebase without a
JS-rendering dependency this project doesn't have.

_KNOWN_VALID_TRIPLES is typed with the Expansion/format_code enums
(not bare strings) deliberately: this table is transcribed by hand
from a scrape, so a typo'd literal (e.g. "PremierDarft") would
otherwise pass silently and only surface as a 404 at download time —
using the enums makes an unrecognized code a NameError/AttributeError
at import time instead. list_known_refs() converts to .value only at
the from_known() call site, since that factory's own signature takes
plain strings (see refs.py).
"""

from src.data_retrieval.seventeenlands.refs import (
    DataType,
    Expansion,
    SeventeenLandsFileRef,
    format_code,
)

_KNOWN_VALID_TRIPLES: frozenset[tuple[DataType, Expansion, format_code]] = frozenset(
    {
        (DataType.DRAFT, Expansion.AFR, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.BLB, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.BLB, format_code.TradDraft),
        (DataType.DRAFT, Expansion.BRO, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.BRO, format_code.TradDraft),
        (DataType.DRAFT, Expansion.Powered_Cube, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.Powered_Cube, format_code.TradDraft),
        (DataType.DRAFT, Expansion.DFT, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.DFT, format_code.TradDraft),
        (DataType.DRAFT, Expansion.DMU, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.DMU, format_code.TradDraft),
        (DataType.DRAFT, Expansion.DSK, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.DSK, format_code.TradDraft),
        (DataType.DRAFT, Expansion.ECL, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.ECL, format_code.TradDraft),
        (DataType.DRAFT, Expansion.EOE, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.EOE, format_code.TradDraft),
        (DataType.DRAFT, Expansion.FDN, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.FDN, format_code.TradDraft),
        (DataType.DRAFT, Expansion.FIN, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.FIN, format_code.TradDraft),
        (DataType.DRAFT, Expansion.HBG, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.HBG, format_code.TradDraft),
        (DataType.DRAFT, Expansion.HOB, format_code.PickTwoDraft),
        (DataType.DRAFT, Expansion.HOB, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.HOB, format_code.TradDraft),
        (DataType.DRAFT, Expansion.KTK, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.KTK, format_code.TradDraft),
        (DataType.DRAFT, Expansion.LCI, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.LCI, format_code.TradDraft),
        (DataType.DRAFT, Expansion.LTR, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.LTR, format_code.TradDraft),
        (DataType.DRAFT, Expansion.MH3, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.MH3, format_code.TradDraft),
        (DataType.DRAFT, Expansion.MID, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.MKM, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.MKM, format_code.TradDraft),
        (DataType.DRAFT, Expansion.MOM, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.MOM, format_code.TradDraft),
        (DataType.DRAFT, Expansion.MSH, format_code.PickTwoDraft),
        (DataType.DRAFT, Expansion.MSH, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.MSH, format_code.TradDraft),
        (DataType.DRAFT, Expansion.NEO, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.NEO, format_code.TradDraft),
        (DataType.DRAFT, Expansion.OM1, format_code.PickTwoDraft),
        (DataType.DRAFT, Expansion.OM1, format_code.PickTwoTradDraft),
        (DataType.DRAFT, Expansion.ONE, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.ONE, format_code.TradDraft),
        (DataType.DRAFT, Expansion.OTJ, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.OTJ, format_code.TradDraft),
        (DataType.DRAFT, Expansion.PIO, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.PIO, format_code.TradDraft),
        (DataType.DRAFT, Expansion.SIR, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.SIR, format_code.TradDraft),
        (DataType.DRAFT, Expansion.SNC, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.SNC, format_code.TradDraft),
        (DataType.DRAFT, Expansion.SOS, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.SOS, format_code.TradDraft),
        (DataType.DRAFT, Expansion.STX, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.STX, format_code.TradDraft),
        (DataType.DRAFT, Expansion.TDM, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.TDM, format_code.TradDraft),
        (DataType.DRAFT, Expansion.TLA, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.TLA, format_code.TradDraft),
        (DataType.DRAFT, Expansion.TMT, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.TMT, format_code.TradDraft),
        (DataType.DRAFT, Expansion.VOW, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.VOW, format_code.QuickDraft),
        (DataType.DRAFT, Expansion.WOE, format_code.PremierDraft),
        (DataType.DRAFT, Expansion.WOE, format_code.TradDraft),
        (DataType.GAME, Expansion.AFR, format_code.PremierDraft),
        (DataType.GAME, Expansion.AFR, format_code.TradDraft),
        (DataType.GAME, Expansion.BLB, format_code.PremierDraft),
        (DataType.GAME, Expansion.BLB, format_code.Sealed),
        (DataType.GAME, Expansion.BLB, format_code.TradDraft),
        (DataType.GAME, Expansion.BLB, format_code.TradSealed),
        (DataType.GAME, Expansion.BRO, format_code.PremierDraft),
        (DataType.GAME, Expansion.BRO, format_code.Sealed),
        (DataType.GAME, Expansion.BRO, format_code.TradDraft),
        (DataType.GAME, Expansion.BRO, format_code.TradSealed),
        (DataType.GAME, Expansion.Powered_Cube, format_code.PremierDraft),
        (DataType.GAME, Expansion.Powered_Cube, format_code.TradDraft),
        (DataType.GAME, Expansion.DFT, format_code.PremierDraft),
        (DataType.GAME, Expansion.DFT, format_code.Sealed),
        (DataType.GAME, Expansion.DFT, format_code.TradDraft),
        (DataType.GAME, Expansion.DFT, format_code.TradSealed),
        (DataType.GAME, Expansion.DMU, format_code.PremierDraft),
        (DataType.GAME, Expansion.DMU, format_code.Sealed),
        (DataType.GAME, Expansion.DMU, format_code.TradDraft),
        (DataType.GAME, Expansion.DMU, format_code.TradSealed),
        (DataType.GAME, Expansion.DSK, format_code.PremierDraft),
        (DataType.GAME, Expansion.DSK, format_code.Sealed),
        (DataType.GAME, Expansion.DSK, format_code.TradDraft),
        (DataType.GAME, Expansion.DSK, format_code.TradSealed),
        (DataType.GAME, Expansion.ECL, format_code.PremierDraft),
        (DataType.GAME, Expansion.ECL, format_code.Sealed),
        (DataType.GAME, Expansion.ECL, format_code.TradDraft),
        (DataType.GAME, Expansion.ECL, format_code.TradSealed),
        (DataType.GAME, Expansion.EOE, format_code.PremierDraft),
        (DataType.GAME, Expansion.EOE, format_code.Sealed),
        (DataType.GAME, Expansion.EOE, format_code.TradDraft),
        (DataType.GAME, Expansion.EOE, format_code.TradSealed),
        (DataType.GAME, Expansion.FDN, format_code.PremierDraft),
        (DataType.GAME, Expansion.FDN, format_code.Sealed),
        (DataType.GAME, Expansion.FDN, format_code.TradDraft),
        (DataType.GAME, Expansion.FDN, format_code.TradSealed),
        (DataType.GAME, Expansion.FIN, format_code.PremierDraft),
        (DataType.GAME, Expansion.FIN, format_code.Sealed),
        (DataType.GAME, Expansion.FIN, format_code.TradDraft),
        (DataType.GAME, Expansion.FIN, format_code.TradSealed),
        (DataType.GAME, Expansion.HBG, format_code.PremierDraft),
        (DataType.GAME, Expansion.HBG, format_code.Sealed),
        (DataType.GAME, Expansion.HBG, format_code.TradDraft),
        (DataType.GAME, Expansion.HBG, format_code.TradSealed),
        (DataType.GAME, Expansion.HOB, format_code.PickTwoDraft),
        (DataType.GAME, Expansion.HOB, format_code.PremierDraft),
        (DataType.GAME, Expansion.HOB, format_code.Sealed),
        (DataType.GAME, Expansion.HOB, format_code.TradDraft),
        (DataType.GAME, Expansion.HOB, format_code.TradSealed),
        (DataType.GAME, Expansion.KHM, format_code.PremierDraft),
        (DataType.GAME, Expansion.KHM, format_code.TradDraft),
        (DataType.GAME, Expansion.KTK, format_code.PremierDraft),
        (DataType.GAME, Expansion.KTK, format_code.Sealed),
        (DataType.GAME, Expansion.KTK, format_code.TradDraft),
        (DataType.GAME, Expansion.KTK, format_code.TradSealed),
        (DataType.GAME, Expansion.LCI, format_code.PremierDraft),
        (DataType.GAME, Expansion.LCI, format_code.Sealed),
        (DataType.GAME, Expansion.LCI, format_code.TradDraft),
        (DataType.GAME, Expansion.LCI, format_code.TradSealed),
        (DataType.GAME, Expansion.LTR, format_code.PremierDraft),
        (DataType.GAME, Expansion.LTR, format_code.Sealed),
        (DataType.GAME, Expansion.LTR, format_code.TradDraft),
        (DataType.GAME, Expansion.LTR, format_code.TradSealed),
        (DataType.GAME, Expansion.MH3, format_code.PremierDraft),
        (DataType.GAME, Expansion.MH3, format_code.Sealed),
        (DataType.GAME, Expansion.MH3, format_code.TradDraft),
        (DataType.GAME, Expansion.MH3, format_code.TradSealed),
        (DataType.GAME, Expansion.MID, format_code.PremierDraft),
        (DataType.GAME, Expansion.MKM, format_code.PremierDraft),
        (DataType.GAME, Expansion.MKM, format_code.Sealed),
        (DataType.GAME, Expansion.MKM, format_code.TradDraft),
        (DataType.GAME, Expansion.MKM, format_code.TradSealed),
        (DataType.GAME, Expansion.MOM, format_code.PremierDraft),
        (DataType.GAME, Expansion.MOM, format_code.Sealed),
        (DataType.GAME, Expansion.MOM, format_code.TradDraft),
        (DataType.GAME, Expansion.MOM, format_code.TradSealed),
        (DataType.GAME, Expansion.MSH, format_code.PickTwoDraft),
        (DataType.GAME, Expansion.MSH, format_code.PremierDraft),
        (DataType.GAME, Expansion.MSH, format_code.Sealed),
        (DataType.GAME, Expansion.MSH, format_code.TradDraft),
        (DataType.GAME, Expansion.MSH, format_code.TradSealed),
        (DataType.GAME, Expansion.NEO, format_code.PremierDraft),
        (DataType.GAME, Expansion.NEO, format_code.Sealed),
        (DataType.GAME, Expansion.NEO, format_code.TradDraft),
        (DataType.GAME, Expansion.OM1, format_code.PickTwoDraft),
        (DataType.GAME, Expansion.OM1, format_code.PickTwoTradDraft),
        (DataType.GAME, Expansion.OM1, format_code.Sealed),
        (DataType.GAME, Expansion.OM1, format_code.TradSealed),
        (DataType.GAME, Expansion.ONE, format_code.PremierDraft),
        (DataType.GAME, Expansion.ONE, format_code.Sealed),
        (DataType.GAME, Expansion.ONE, format_code.TradDraft),
        (DataType.GAME, Expansion.ONE, format_code.TradSealed),
        (DataType.GAME, Expansion.OTJ, format_code.PremierDraft),
        (DataType.GAME, Expansion.OTJ, format_code.Sealed),
        (DataType.GAME, Expansion.OTJ, format_code.TradDraft),
        (DataType.GAME, Expansion.OTJ, format_code.TradSealed),
        (DataType.GAME, Expansion.PIO, format_code.PremierDraft),
        (DataType.GAME, Expansion.PIO, format_code.Sealed),
        (DataType.GAME, Expansion.PIO, format_code.TradDraft),
        (DataType.GAME, Expansion.PIO, format_code.TradSealed),
        (DataType.GAME, Expansion.SIR, format_code.PremierDraft),
        (DataType.GAME, Expansion.SIR, format_code.Sealed),
        (DataType.GAME, Expansion.SIR, format_code.TradDraft),
        (DataType.GAME, Expansion.SIR, format_code.TradSealed),
        (DataType.GAME, Expansion.SNC, format_code.PremierDraft),
        (DataType.GAME, Expansion.SNC, format_code.Sealed),
        (DataType.GAME, Expansion.SNC, format_code.TradDraft),
        (DataType.GAME, Expansion.SNC, format_code.TradSealed),
        (DataType.GAME, Expansion.SOS, format_code.PremierDraft),
        (DataType.GAME, Expansion.SOS, format_code.Sealed),
        (DataType.GAME, Expansion.SOS, format_code.TradDraft),
        (DataType.GAME, Expansion.SOS, format_code.TradSealed),
        (DataType.GAME, Expansion.STX, format_code.PremierDraft),
        (DataType.GAME, Expansion.STX, format_code.Sealed),
        (DataType.GAME, Expansion.STX, format_code.TradDraft),
        (DataType.GAME, Expansion.STX, format_code.TradSealed),
        (DataType.GAME, Expansion.TDM, format_code.PremierDraft),
        (DataType.GAME, Expansion.TDM, format_code.Sealed),
        (DataType.GAME, Expansion.TDM, format_code.TradDraft),
        (DataType.GAME, Expansion.TDM, format_code.TradSealed),
        (DataType.GAME, Expansion.TLA, format_code.PremierDraft),
        (DataType.GAME, Expansion.TLA, format_code.Sealed),
        (DataType.GAME, Expansion.TLA, format_code.TradDraft),
        (DataType.GAME, Expansion.TLA, format_code.TradSealed),
        (DataType.GAME, Expansion.TMT, format_code.PremierDraft),
        (DataType.GAME, Expansion.TMT, format_code.Sealed),
        (DataType.GAME, Expansion.TMT, format_code.TradDraft),
        (DataType.GAME, Expansion.TMT, format_code.TradSealed),
        (DataType.GAME, Expansion.VOW, format_code.PremierDraft),
        (DataType.GAME, Expansion.WOE, format_code.PremierDraft),
        (DataType.GAME, Expansion.WOE, format_code.Sealed),
        (DataType.GAME, Expansion.WOE, format_code.TradDraft),
        (DataType.GAME, Expansion.WOE, format_code.TradSealed),
        (DataType.REPLAY, Expansion.AFR, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.AFR, format_code.TradDraft),
        (DataType.REPLAY, Expansion.BLB, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.BLB, format_code.Sealed),
        (DataType.REPLAY, Expansion.BLB, format_code.TradDraft),
        (DataType.REPLAY, Expansion.BLB, format_code.TradSealed),
        (DataType.REPLAY, Expansion.Powered_Cube, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.Powered_Cube, format_code.TradDraft),
        (DataType.REPLAY, Expansion.DFT, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.DFT, format_code.Sealed),
        (DataType.REPLAY, Expansion.DFT, format_code.TradDraft),
        (DataType.REPLAY, Expansion.DFT, format_code.TradSealed),
        (DataType.REPLAY, Expansion.DMU, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.DMU, format_code.Sealed),
        (DataType.REPLAY, Expansion.DMU, format_code.TradDraft),
        (DataType.REPLAY, Expansion.DMU, format_code.TradSealed),
        (DataType.REPLAY, Expansion.DSK, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.DSK, format_code.Sealed),
        (DataType.REPLAY, Expansion.DSK, format_code.TradDraft),
        (DataType.REPLAY, Expansion.DSK, format_code.TradSealed),
        (DataType.REPLAY, Expansion.EOE, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.EOE, format_code.Sealed),
        (DataType.REPLAY, Expansion.EOE, format_code.TradDraft),
        (DataType.REPLAY, Expansion.EOE, format_code.TradSealed),
        (DataType.REPLAY, Expansion.FDN, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.FDN, format_code.Sealed),
        (DataType.REPLAY, Expansion.FDN, format_code.TradDraft),
        (DataType.REPLAY, Expansion.FDN, format_code.TradSealed),
        (DataType.REPLAY, Expansion.FIN, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.FIN, format_code.Sealed),
        (DataType.REPLAY, Expansion.FIN, format_code.TradDraft),
        (DataType.REPLAY, Expansion.FIN, format_code.TradSealed),
        (DataType.REPLAY, Expansion.KTK, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.KTK, format_code.Sealed),
        (DataType.REPLAY, Expansion.KTK, format_code.TradDraft),
        (DataType.REPLAY, Expansion.KTK, format_code.TradSealed),
        (DataType.REPLAY, Expansion.LCI, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.LCI, format_code.Sealed),
        (DataType.REPLAY, Expansion.LCI, format_code.TradDraft),
        (DataType.REPLAY, Expansion.LCI, format_code.TradSealed),
        (DataType.REPLAY, Expansion.LTR, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.LTR, format_code.Sealed),
        (DataType.REPLAY, Expansion.LTR, format_code.TradDraft),
        (DataType.REPLAY, Expansion.LTR, format_code.TradSealed),
        (DataType.REPLAY, Expansion.MH3, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.MH3, format_code.Sealed),
        (DataType.REPLAY, Expansion.MH3, format_code.TradDraft),
        (DataType.REPLAY, Expansion.MH3, format_code.TradSealed),
        (DataType.REPLAY, Expansion.MKM, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.MKM, format_code.Sealed),
        (DataType.REPLAY, Expansion.MKM, format_code.TradDraft),
        (DataType.REPLAY, Expansion.MKM, format_code.TradSealed),
        (DataType.REPLAY, Expansion.MOM, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.MOM, format_code.Sealed),
        (DataType.REPLAY, Expansion.MOM, format_code.TradDraft),
        (DataType.REPLAY, Expansion.MOM, format_code.TradSealed),
        (DataType.REPLAY, Expansion.MSH, format_code.PickTwoDraft),
        (DataType.REPLAY, Expansion.MSH, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.MSH, format_code.Sealed),
        (DataType.REPLAY, Expansion.MSH, format_code.TradDraft),
        (DataType.REPLAY, Expansion.MSH, format_code.TradSealed),
        (DataType.REPLAY, Expansion.OM1, format_code.PickTwoDraft),
        (DataType.REPLAY, Expansion.OM1, format_code.PickTwoTradDraft),
        (DataType.REPLAY, Expansion.OM1, format_code.Sealed),
        (DataType.REPLAY, Expansion.OM1, format_code.TradSealed),
        (DataType.REPLAY, Expansion.OTJ, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.OTJ, format_code.Sealed),
        (DataType.REPLAY, Expansion.OTJ, format_code.TradDraft),
        (DataType.REPLAY, Expansion.OTJ, format_code.TradSealed),
        (DataType.REPLAY, Expansion.PIO, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.PIO, format_code.Sealed),
        (DataType.REPLAY, Expansion.PIO, format_code.TradDraft),
        (DataType.REPLAY, Expansion.PIO, format_code.TradSealed),
        (DataType.REPLAY, Expansion.SIR, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.SIR, format_code.Sealed),
        (DataType.REPLAY, Expansion.SIR, format_code.TradDraft),
        (DataType.REPLAY, Expansion.SIR, format_code.TradSealed),
        (DataType.REPLAY, Expansion.SNC, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.SOS, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.SOS, format_code.Sealed),
        (DataType.REPLAY, Expansion.SOS, format_code.TradDraft),
        (DataType.REPLAY, Expansion.SOS, format_code.TradSealed),
        (DataType.REPLAY, Expansion.STX, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.STX, format_code.TradDraft),
        (DataType.REPLAY, Expansion.TDM, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.TDM, format_code.Sealed),
        (DataType.REPLAY, Expansion.TDM, format_code.TradDraft),
        (DataType.REPLAY, Expansion.TDM, format_code.TradSealed),
        (DataType.REPLAY, Expansion.TLA, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.TLA, format_code.Sealed),
        (DataType.REPLAY, Expansion.TLA, format_code.TradDraft),
        (DataType.REPLAY, Expansion.TLA, format_code.TradSealed),
        (DataType.REPLAY, Expansion.TMT, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.TMT, format_code.Sealed),
        (DataType.REPLAY, Expansion.TMT, format_code.TradDraft),
        (DataType.REPLAY, Expansion.TMT, format_code.TradSealed),
        (DataType.REPLAY, Expansion.WOE, format_code.PremierDraft),
        (DataType.REPLAY, Expansion.WOE, format_code.Sealed),
        (DataType.REPLAY, Expansion.WOE, format_code.TradDraft),
        (DataType.REPLAY, Expansion.WOE, format_code.TradSealed),
    }
)


def list_known_refs() -> list[SeventeenLandsFileRef]:
    """Build every SeventeenLandsFileRef in _KNOWN_VALID_TRIPLES.

    Inputs: none.
    Output: one SeventeenLandsFileRef per entry in
        _KNOWN_VALID_TRIPLES, sorted by (data_type, expansion,
        format_code) for deterministic ordering — this list feeds
        SeventeenLandsDownloader.download()'s tqdm progress bar, where
        a stable order makes repeated runs easier to compare.
    Side effects: none — no network I/O, this is a static table.
    Exceptions: none.

    Example:
        >>> refs = list_known_refs()
        >>> len(refs)
        303
    """
    return [
        SeventeenLandsFileRef.from_known(data_type, expansion.value, fmt.value)
        for data_type, expansion, fmt in sorted(
            _KNOWN_VALID_TRIPLES,
            key=lambda triple: (triple[0].value, triple[1].value, triple[2].value),
        )
    ]
