"""A static snapshot of every (data_type, expansion, format_code) triple
17Lands has actually published a file for, as of 2026-09-06.

Third way to produce SeventeenLandsFileRefs, alongside the two
described in refs.py's module docstring. Exists because validity here
isn't systematic — e.g. STX+Sealed only ever got a GAME file, never
DRAFT or REPLAY — so neither "try the full cartesian product of every
enum value" nor a runtime fetch can derive it:
https://www.17lands.com/public_datasets is a client-rendered SPA (its
table is populated by JS after load), so a plain GET returns an empty
shell with no links in it — LandingPageParser can't be pointed at the
live URL directly. This table was produced by saving that page's
fully-rendered HTML (from a real browser) to disk and running
LandingPageParser against the saved file once, by hand.

To refresh: open https://www.17lands.com/public_datasets in a browser,
save the fully-rendered page HTML, then re-run LandingPageParser().parse()
against it and regenerate _KNOWN_VALID_TRIPLES below. There's no way to
automate that refresh from within this codebase without a
JS-rendering dependency this project doesn't have.

_KNOWN_VALID_TRIPLES is typed with the Expansion/FormatCode enums
(not bare strings) deliberately: this table is transcribed by hand
from a scrape, so a typo'd literal (e.g. "PremierDarft") would
otherwise pass silently and only surface as a 404 at download time —
using the enums makes an unrecognized code a NameError/AttributeError
at import time instead. list_known_refs() converts to .value only at
the from_known() call site, since that factory's own signature takes
plain strings (see refs.py).
"""

from src.data_retrieval.seventeenlands.refs import (
    DataType,
    Expansion,
    FormatCode,
    SeventeenLandsFileRef,
)

_KNOWN_VALID_TRIPLES: frozenset[tuple[DataType, Expansion, FormatCode]] = frozenset(
    {
        (DataType.DRAFT, Expansion.AFR, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.BLB, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.BLB, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.BRO, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.BRO, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.Powered_Cube, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.Powered_Cube, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.DFT, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.DFT, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.DMU, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.DMU, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.DSK, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.DSK, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.ECL, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.ECL, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.EOE, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.EOE, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.FDN, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.FDN, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.FIN, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.FIN, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.HBG, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.HBG, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.HOB, FormatCode.PickTwoDraft),
        (DataType.DRAFT, Expansion.HOB, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.HOB, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.KTK, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.KTK, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.LCI, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.LCI, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.LTR, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.LTR, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.MH3, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.MH3, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.MID, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.MKM, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.MKM, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.MOM, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.MOM, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.MSH, FormatCode.PickTwoDraft),
        (DataType.DRAFT, Expansion.MSH, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.MSH, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.NEO, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.NEO, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.OM1, FormatCode.PickTwoDraft),
        (DataType.DRAFT, Expansion.OM1, FormatCode.PickTwoTradDraft),
        (DataType.DRAFT, Expansion.ONE, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.ONE, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.OTJ, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.OTJ, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.PIO, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.PIO, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.SIR, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.SIR, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.SNC, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.SNC, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.SOS, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.SOS, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.STX, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.STX, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.TDM, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.TDM, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.TLA, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.TLA, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.TMT, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.TMT, FormatCode.TradDraft),
        (DataType.DRAFT, Expansion.VOW, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.VOW, FormatCode.QuickDraft),
        (DataType.DRAFT, Expansion.WOE, FormatCode.PremierDraft),
        (DataType.DRAFT, Expansion.WOE, FormatCode.TradDraft),
        (DataType.GAME, Expansion.AFR, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.AFR, FormatCode.TradDraft),
        (DataType.GAME, Expansion.BLB, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.BLB, FormatCode.Sealed),
        (DataType.GAME, Expansion.BLB, FormatCode.TradDraft),
        (DataType.GAME, Expansion.BLB, FormatCode.TradSealed),
        (DataType.GAME, Expansion.BRO, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.BRO, FormatCode.Sealed),
        (DataType.GAME, Expansion.BRO, FormatCode.TradDraft),
        (DataType.GAME, Expansion.BRO, FormatCode.TradSealed),
        (DataType.GAME, Expansion.Powered_Cube, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.Powered_Cube, FormatCode.TradDraft),
        (DataType.GAME, Expansion.DFT, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.DFT, FormatCode.Sealed),
        (DataType.GAME, Expansion.DFT, FormatCode.TradDraft),
        (DataType.GAME, Expansion.DFT, FormatCode.TradSealed),
        (DataType.GAME, Expansion.DMU, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.DMU, FormatCode.Sealed),
        (DataType.GAME, Expansion.DMU, FormatCode.TradDraft),
        (DataType.GAME, Expansion.DMU, FormatCode.TradSealed),
        (DataType.GAME, Expansion.DSK, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.DSK, FormatCode.Sealed),
        (DataType.GAME, Expansion.DSK, FormatCode.TradDraft),
        (DataType.GAME, Expansion.DSK, FormatCode.TradSealed),
        (DataType.GAME, Expansion.ECL, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.ECL, FormatCode.Sealed),
        (DataType.GAME, Expansion.ECL, FormatCode.TradDraft),
        (DataType.GAME, Expansion.ECL, FormatCode.TradSealed),
        (DataType.GAME, Expansion.EOE, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.EOE, FormatCode.Sealed),
        (DataType.GAME, Expansion.EOE, FormatCode.TradDraft),
        (DataType.GAME, Expansion.EOE, FormatCode.TradSealed),
        (DataType.GAME, Expansion.FDN, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.FDN, FormatCode.Sealed),
        (DataType.GAME, Expansion.FDN, FormatCode.TradDraft),
        (DataType.GAME, Expansion.FDN, FormatCode.TradSealed),
        (DataType.GAME, Expansion.FIN, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.FIN, FormatCode.Sealed),
        (DataType.GAME, Expansion.FIN, FormatCode.TradDraft),
        (DataType.GAME, Expansion.FIN, FormatCode.TradSealed),
        (DataType.GAME, Expansion.HBG, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.HBG, FormatCode.Sealed),
        (DataType.GAME, Expansion.HBG, FormatCode.TradDraft),
        (DataType.GAME, Expansion.HBG, FormatCode.TradSealed),
        (DataType.GAME, Expansion.HOB, FormatCode.PickTwoDraft),
        (DataType.GAME, Expansion.HOB, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.HOB, FormatCode.Sealed),
        (DataType.GAME, Expansion.HOB, FormatCode.TradDraft),
        (DataType.GAME, Expansion.HOB, FormatCode.TradSealed),
        (DataType.GAME, Expansion.KHM, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.KHM, FormatCode.TradDraft),
        (DataType.GAME, Expansion.KTK, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.KTK, FormatCode.Sealed),
        (DataType.GAME, Expansion.KTK, FormatCode.TradDraft),
        (DataType.GAME, Expansion.KTK, FormatCode.TradSealed),
        (DataType.GAME, Expansion.LCI, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.LCI, FormatCode.Sealed),
        (DataType.GAME, Expansion.LCI, FormatCode.TradDraft),
        (DataType.GAME, Expansion.LCI, FormatCode.TradSealed),
        (DataType.GAME, Expansion.LTR, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.LTR, FormatCode.Sealed),
        (DataType.GAME, Expansion.LTR, FormatCode.TradDraft),
        (DataType.GAME, Expansion.LTR, FormatCode.TradSealed),
        (DataType.GAME, Expansion.MH3, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.MH3, FormatCode.Sealed),
        (DataType.GAME, Expansion.MH3, FormatCode.TradDraft),
        (DataType.GAME, Expansion.MH3, FormatCode.TradSealed),
        (DataType.GAME, Expansion.MID, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.MKM, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.MKM, FormatCode.Sealed),
        (DataType.GAME, Expansion.MKM, FormatCode.TradDraft),
        (DataType.GAME, Expansion.MKM, FormatCode.TradSealed),
        (DataType.GAME, Expansion.MOM, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.MOM, FormatCode.Sealed),
        (DataType.GAME, Expansion.MOM, FormatCode.TradDraft),
        (DataType.GAME, Expansion.MOM, FormatCode.TradSealed),
        (DataType.GAME, Expansion.MSH, FormatCode.PickTwoDraft),
        (DataType.GAME, Expansion.MSH, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.MSH, FormatCode.Sealed),
        (DataType.GAME, Expansion.MSH, FormatCode.TradDraft),
        (DataType.GAME, Expansion.MSH, FormatCode.TradSealed),
        (DataType.GAME, Expansion.NEO, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.NEO, FormatCode.Sealed),
        (DataType.GAME, Expansion.NEO, FormatCode.TradDraft),
        (DataType.GAME, Expansion.OM1, FormatCode.PickTwoDraft),
        (DataType.GAME, Expansion.OM1, FormatCode.PickTwoTradDraft),
        (DataType.GAME, Expansion.OM1, FormatCode.Sealed),
        (DataType.GAME, Expansion.OM1, FormatCode.TradSealed),
        (DataType.GAME, Expansion.ONE, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.ONE, FormatCode.Sealed),
        (DataType.GAME, Expansion.ONE, FormatCode.TradDraft),
        (DataType.GAME, Expansion.ONE, FormatCode.TradSealed),
        (DataType.GAME, Expansion.OTJ, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.OTJ, FormatCode.Sealed),
        (DataType.GAME, Expansion.OTJ, FormatCode.TradDraft),
        (DataType.GAME, Expansion.OTJ, FormatCode.TradSealed),
        (DataType.GAME, Expansion.PIO, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.PIO, FormatCode.Sealed),
        (DataType.GAME, Expansion.PIO, FormatCode.TradDraft),
        (DataType.GAME, Expansion.PIO, FormatCode.TradSealed),
        (DataType.GAME, Expansion.SIR, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.SIR, FormatCode.Sealed),
        (DataType.GAME, Expansion.SIR, FormatCode.TradDraft),
        (DataType.GAME, Expansion.SIR, FormatCode.TradSealed),
        (DataType.GAME, Expansion.SNC, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.SNC, FormatCode.Sealed),
        (DataType.GAME, Expansion.SNC, FormatCode.TradDraft),
        (DataType.GAME, Expansion.SNC, FormatCode.TradSealed),
        (DataType.GAME, Expansion.SOS, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.SOS, FormatCode.Sealed),
        (DataType.GAME, Expansion.SOS, FormatCode.TradDraft),
        (DataType.GAME, Expansion.SOS, FormatCode.TradSealed),
        (DataType.GAME, Expansion.STX, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.STX, FormatCode.Sealed),
        (DataType.GAME, Expansion.STX, FormatCode.TradDraft),
        (DataType.GAME, Expansion.STX, FormatCode.TradSealed),
        (DataType.GAME, Expansion.TDM, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.TDM, FormatCode.Sealed),
        (DataType.GAME, Expansion.TDM, FormatCode.TradDraft),
        (DataType.GAME, Expansion.TDM, FormatCode.TradSealed),
        (DataType.GAME, Expansion.TLA, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.TLA, FormatCode.Sealed),
        (DataType.GAME, Expansion.TLA, FormatCode.TradDraft),
        (DataType.GAME, Expansion.TLA, FormatCode.TradSealed),
        (DataType.GAME, Expansion.TMT, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.TMT, FormatCode.Sealed),
        (DataType.GAME, Expansion.TMT, FormatCode.TradDraft),
        (DataType.GAME, Expansion.TMT, FormatCode.TradSealed),
        (DataType.GAME, Expansion.VOW, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.WOE, FormatCode.PremierDraft),
        (DataType.GAME, Expansion.WOE, FormatCode.Sealed),
        (DataType.GAME, Expansion.WOE, FormatCode.TradDraft),
        (DataType.GAME, Expansion.WOE, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.AFR, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.AFR, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.BLB, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.BLB, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.BLB, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.BLB, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.Powered_Cube, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.Powered_Cube, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.DFT, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.DFT, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.DFT, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.DFT, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.DMU, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.DMU, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.DMU, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.DMU, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.DSK, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.DSK, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.DSK, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.DSK, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.EOE, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.EOE, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.EOE, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.EOE, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.FDN, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.FDN, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.FDN, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.FDN, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.FIN, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.FIN, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.FIN, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.FIN, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.KTK, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.KTK, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.KTK, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.KTK, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.LCI, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.LCI, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.LCI, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.LCI, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.LTR, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.LTR, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.LTR, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.LTR, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.MH3, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.MH3, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.MH3, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.MH3, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.MKM, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.MKM, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.MKM, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.MKM, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.MOM, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.MOM, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.MOM, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.MOM, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.MSH, FormatCode.PickTwoDraft),
        (DataType.REPLAY, Expansion.MSH, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.MSH, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.MSH, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.MSH, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.OM1, FormatCode.PickTwoDraft),
        (DataType.REPLAY, Expansion.OM1, FormatCode.PickTwoTradDraft),
        (DataType.REPLAY, Expansion.OM1, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.OM1, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.OTJ, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.OTJ, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.OTJ, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.OTJ, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.PIO, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.PIO, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.PIO, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.PIO, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.SIR, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.SIR, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.SIR, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.SIR, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.SNC, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.SOS, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.SOS, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.SOS, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.SOS, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.STX, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.STX, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.TDM, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.TDM, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.TDM, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.TDM, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.TLA, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.TLA, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.TLA, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.TLA, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.TMT, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.TMT, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.TMT, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.TMT, FormatCode.TradSealed),
        (DataType.REPLAY, Expansion.WOE, FormatCode.PremierDraft),
        (DataType.REPLAY, Expansion.WOE, FormatCode.Sealed),
        (DataType.REPLAY, Expansion.WOE, FormatCode.TradDraft),
        (DataType.REPLAY, Expansion.WOE, FormatCode.TradSealed),
    }
)


def list_known_refs() -> list[SeventeenLandsFileRef]:
    """Build every SeventeenLandsFileRef in _KNOWN_VALID_TRIPLES.

    Inputs: none.
    Output: one SeventeenLandsFileRef per entry in
        _KNOWN_VALID_TRIPLES, sorted by (data_type, expansion,
        format_code) for deterministic ordering — this list feeds
        SeventeenLandsDownloader.download()'s tqdm progress bar, where
        a stable order makes repeated runs easier to compare.
    Side effects: none — no network I/O, this is a static table.
    Exceptions: none.

    Example:
        >>> refs = list_known_refs()
        >>> len(refs)
        303
    """
    return [
        SeventeenLandsFileRef.from_known(data_type, expansion.value, fmt.value)
        for data_type, expansion, fmt in sorted(
            _KNOWN_VALID_TRIPLES,
            key=lambda triple: (triple[0].value, triple[1].value, triple[2].value),
        )
    ]
