"""The multi-game deck store, backed by one SQLite file per game.

See plans/deckbox_sqlite.md for the full design this implements (the
architecture discussion that motivated it, and the corrections made
after two rounds of critic review), and
src/data_refinement/card_binder/card_binder.py for the sibling this was
originally modeled on. DeckBox mirrors CardBinder's CRUD-by-uuid shape
only - it has NO AliasLedger and NO identity-collision handling of any
kind, because decks don't have the problem CardBinder's non-trivial
half exists to solve (see this container's README).

THIS FILE WAS REWRITTEN from a pure in-memory dict
(dict[UUID, GenericDeck]) onto SQLite - the in-memory version could not
scale to seventeenlands_game_data's ~15-20M decks, and more importantly
could never scale to the eventual goal of one combined DeckBox holding
every MTG source, since load()/all_decks()/get_by_uuid() all assumed
full in-memory residency for every future operation, not just first
population.

THE LOAD/SAVE RELATIONSHIP, precisely (see load()/save()'s own
docstrings for the authoritative statement):
    - DeckBox() / load([]): a fresh ":memory:" connection, no path
      association.
    - load([one_path]): ALWAYS connects directly to one_path, whether
      or not it exists yet. From that point on, every mutating call
      (create/create_if_absent/update/replace/delete) wraps its own
      row write(s) - its own deck row, its deck_cards rows, and any
      metadata invalidation - in `with self._connection:`, which
      commits ONCE on a clean return and rolls back everything that
      call touched if it raises OR if the process is killed before
      that point - either way, the database ends up exactly as if the
      call had never been made, never a half-written row. There is no
      separate in-memory representation to flush. This is deliberate:
      an earlier design only direct-connected when one_path already
      existed, which meant a brand-new source's first-ever ingestion
      still accumulated entirely in memory and lost everything on a
      crash - exactly the failure this rewrite exists to fix.
    - load([2+ paths]): always a fresh ":memory:" merge. No given path
      is ever mutated - this is a genuine read, unlike the single-path
      case above.

CRASH-SAFETY OF THE VERSION STAMP: because a single-path box now
persists writes immediately, a run that crashes partway through
updating an EXISTING box must not leave metadata.card_binder_version
claiming a version that no longer accurately describes every row. Every
mutating call touching a given source_game clears (deletes) that game's
metadata row, inside the same `with self._connection:` block as the row
write(s) that follow it (unconditionally - deleting an already-absent
row is a cheap no-op, not something worth caching "already done" for;
see _invalidate_metadata_if_needed()'s own docstring for why a
Python-side cache was tried and removed). A pure-read session never
touches metadata. A crash - or a caught, retried exception - mid-write
therefore leaves metadata ABSENT for that game rather than falsely
matching a stale version - card_binder_version_for() returning None for
an absent
row is the existing, documented contract, and existing callers already
treat None as untrustworthy (see e.g.
src/dojos/contrastive/dojo.py's ContrastiveDojo._check_deck_box_version()).
save() re-establishes the row only once a run completes without error.

THIS MAKES IDEMPOTENT-RETRY A LOAD-BEARING ASSUMPTION, not just a nice
property: a crash-then-retry only converges to correct final content
because every current DeckExtractionStage derives a deterministic
identity and does get_by_uuid()-then-create()-or-update() (see
extraction.py's own docstring). A hypothetical future stage using
create() with a fresh, non-deterministic uuid per row would silently
duplicate content on any crash+retry under this direct-connect model -
previously harmless under the old load-everything/save-once model,
since it never left partial writes on disk for a retry to encounter.

A nocab_uuid, once minted for a deck, is never regenerated by anything
in this file - a save()/load() round-trip returns the exact same uuid
for the exact same deck, always.
"""

import hashlib
import json
import secrets
import sqlite3
from collections import Counter
from dataclasses import replace
from datetime import datetime
from pathlib import Path
from typing import ClassVar, Iterator
from uuid import UUID

from src.schema.card import GenericDeck, Provenance
from src.schema.data_source import DataSource
from src.schema.game_id import GameId

# decks/deck_cards/metadata - see this module's docstring and
# plans/deckbox_sqlite.md's contract manifest for the design behind
# this exact shape. IF NOT EXISTS throughout: _create_schema() runs on
# every connection this class opens, including one already holding
# this schema from a prior run.
_SCHEMA_DDL = """
CREATE TABLE IF NOT EXISTS decks (
    nocab_uuid TEXT PRIMARY KEY,
    source_game TEXT NOT NULL,
    name TEXT NOT NULL,
    provenance_data_source TEXT,
    provenance_source_id TEXT,
    provenance_fetched_at TEXT
);

CREATE TABLE IF NOT EXISTS deck_cards (
    deck_uuid TEXT NOT NULL REFERENCES decks(nocab_uuid),
    card_uuid TEXT NOT NULL,
    count INTEGER NOT NULL,
    PRIMARY KEY (deck_uuid, card_uuid)
);
CREATE INDEX IF NOT EXISTS idx_deck_cards_deck_uuid ON deck_cards(deck_uuid);

CREATE TABLE IF NOT EXISTS metadata (
    source_game TEXT PRIMARY KEY,
    card_binder_version TEXT NOT NULL
);
"""

# Name _register_seeded_order_function() registers on a connection and
# _stream_ranked_deck_rows() sorts by - see uuids_ranked_randomly()'s
# docstring for why this exists instead of SQLite's own RANDOM().
_SEEDED_ORDER_FUNCTION_NAME = "deckbox_seeded_order"


class DeckBox:
    """Multi-game deck store, backed by one SQLite file per game.

    Single-consumer-per-instance is not the right frame here - this is
    the shared, generic storage capability every deck_box extraction
    stage (and, eventually, training) reads from and writes into.
    Construction is always empty and unconnected to any file
    (__init__ takes no arguments); load() is the sole entry point that
    connects a box to real, persisted content.
    """

    DEFAULT_OUTPUT_DIR: ClassVar[Path] = Path("data/final/decks")
    # Changed from "{game}.jsonl" - this container's saved boxes are
    # now SQLite files, not JSONL.
    DEFAULT_OUTPUT_NAME: ClassVar[str] = "{game}.db"

    def __init__(self) -> None:
        """Construct an empty deck box, backed by an in-memory SQLite database.

        Prefer load([]) over calling this directly when the intent is
        "start empty for an extraction run" - this constructor exists
        because load() is itself built on top of it.

        Inputs: none.
        Output: none (constructor).
        Side effects: opens a fresh ":memory:" SQLite connection and
            creates this box's schema (decks/deck_cards/metadata) on
            it.
        Exceptions: none.
        """
        self._connection = sqlite3.connect(":memory:")
        # None means "not connected to any real file" (see this
        # class's docstring's load/save relationship) - save()'s
        # narrow-vs-copy branch keys off this.
        self._path: Path | None = None
        self._create_schema()

    # region CRUD by UUID

    def create(self, deck: GenericDeck) -> GenericDeck:
        """Insert a brand-new deck.

        Callers (DeckExtractionStage implementations) are expected to
        have already determined that deck.nocab_uuid is genuinely new
        - this method exists to catch the mistake of calling it twice
        for the same uuid, not to perform that determination itself.

        Inputs:
            deck: the deck to insert. deck.nocab_uuid MUST NOT already
                be stored.
        Output: deck, unchanged (returned for symmetry with
            update()/replace(), which do return a possibly-different
            object).
        Side effects: mutates this box's store inside a `with
            self._connection:` block - deck's own row, its deck_cards
            rows, and (if this is the first mutating call this session
            for deck.source_game) clearing that game's metadata row all
            commit together on success, or all roll back together if
            this call raises partway through OR the process is killed
            before the block exits (see this class's docstring's
            crash-safety section) - either way, never a half-written
            row. The duplicate-uuid check happens BEFORE this block: a
            rejected (raising) call never opens it and leaves the store
            untouched.
        Exceptions: raises ValueError if deck.nocab_uuid is already
            stored - use update() or replace() instead.

        Example:
            >>> box = DeckBox()
            >>> box.create(some_deck)
        """
        # A duplicate create() is a caller mistake, not a legitimate
        # case - create_if_absent() exists for the "recurrence is
        # fine" case instead. Checked BEFORE invalidating metadata: a
        # rejected call never writes, so it must not pay the cost of
        # clearing the version stamp either.
        if self._deck_row_exists(deck.nocab_uuid):
            raise ValueError(f"create: {deck.nocab_uuid} is already stored")

        with self._connection:
            self._invalidate_metadata_if_needed(deck.source_game)
            self._insert_deck_row(deck)
            self._insert_deck_cards_rows(deck.nocab_uuid, deck.card_nocab_uuids)
        return deck

    def create_if_absent(self, deck: GenericDeck) -> GenericDeck:
        """Insert deck only if deck.nocab_uuid isn't already stored.

        The counterpart to create() for callers whose id scheme is
        deliberately content-derived and therefore expect the same id
        to legitimately recur across many calls. On a recurrence,
        deck is NOT compared against the stored value for equality -
        the existing entry wins unconditionally.

        Inputs:
            deck: the deck to insert if deck.nocab_uuid is new.
        Output: the deck now stored under deck.nocab_uuid - deck
            itself on a genuinely new id, or whatever was already
            stored on a recurrence.
        Side effects: mutates this box's store only when
            deck.nocab_uuid is new, inside a `with self._connection:`
            block (see create()'s docstring) that also clears
            deck.source_game's metadata row if needed - a recurrence is
            the expected, non-error path
            here and must not pay that cost.
        Exceptions: none.

        Example:
            >>> box = DeckBox()
            >>> box.create_if_absent(some_deck)
            >>> box.create_if_absent(some_deck)  # no-op, same id
        """
        existing = self.get_by_uuid(deck.nocab_uuid)
        if existing is not None:
            return existing

        with self._connection:
            self._invalidate_metadata_if_needed(deck.source_game)
            self._insert_deck_row(deck)
            self._insert_deck_cards_rows(deck.nocab_uuid, deck.card_nocab_uuids)
        return deck

    def update(
        self,
        nocab_uuid: UUID,
        card_nocab_uuids: list[UUID] | None = None,
        name: str | None = None,
        provenance: Provenance | None = None,
    ) -> GenericDeck:
        """Selectively overwrite fields of an already-stored deck.

        "Update" here means "overwrite whichever of
        card_nocab_uuids/name/provenance are given (not None), leave
        the rest untouched" - the closest equivalent for a dataclass
        with only scalar/list fields. This is the "leave other fields
        alone" counterpart to replace()'s full swap.

        Inputs:
            nocab_uuid: identity of the deck to update. MUST already
                be stored.
            card_nocab_uuids: new full list of card nocab_uuids
                (unordered, duplicates meaningful), or None (default)
                to leave unchanged. REPLACES the existing list wholesale.
            name: new name, or None (default) to leave unchanged.
            provenance: new provenance, or None (default) to leave
                unchanged.
        Output: the updated GenericDeck as now stored.
        Side effects: mutates this box's store inside a `with
            self._connection:` block, same as create() - see its
            docstring.
        Exceptions: raises KeyError if nocab_uuid isn't stored.

        Example:
            >>> box = DeckBox()
            >>> box.create(some_deck)
            >>> box.update(some_deck.nocab_uuid, name="Renamed Deck")
        """
        existing = self.get_by_uuid(nocab_uuid)
        if existing is None:
            raise KeyError(f"update: {nocab_uuid} is not stored")

        updated = replace(
            existing,
            card_nocab_uuids=(
                card_nocab_uuids
                if card_nocab_uuids is not None
                else existing.card_nocab_uuids
            ),
            name=name if name is not None else existing.name,
            provenance=(provenance if provenance is not None else existing.provenance),
        )

        with self._connection:
            self._invalidate_metadata_if_needed(existing.source_game)
            self._update_deck_row(updated)
            if card_nocab_uuids is not None:
                self._replace_deck_cards_rows(nocab_uuid, card_nocab_uuids)
        return updated

    def replace(self, nocab_uuid: UUID, deck: GenericDeck) -> GenericDeck:
        """Fully overwrite an already-stored deck's content.

        Every field of deck becomes the stored value for nocab_uuid -
        conceptually a delete-then-add, except nocab_uuid itself never
        changes.

        Inputs:
            nocab_uuid: identity of the deck to replace. MUST already
                be stored.
            deck: the new full deck content. deck.nocab_uuid MUST
                equal nocab_uuid.
        Output: deck, unchanged.
        Side effects: mutates this box's store inside a `with
            self._connection:` block, same as create() - see its
            docstring.
        Exceptions: raises KeyError if nocab_uuid isn't stored. Raises
            ValueError if deck.nocab_uuid != nocab_uuid.

        Example:
            >>> box = DeckBox()
            >>> box.create(some_deck)
            >>> box.replace(some_deck.nocab_uuid, updated_deck)
        """
        if deck.nocab_uuid != nocab_uuid:
            raise ValueError(
                f"replace: deck.nocab_uuid ({deck.nocab_uuid}) != target uuid ({nocab_uuid})"
            )
        existing = self.get_by_uuid(nocab_uuid)
        if existing is None:
            raise KeyError(f"replace: {nocab_uuid} is not stored")

        with self._connection:
            self._invalidate_metadata_if_needed(deck.source_game)
            self._update_deck_row(deck)
            self._replace_deck_cards_rows(nocab_uuid, deck.card_nocab_uuids)
        return deck

    def delete(self, nocab_uuid: UUID) -> None:
        """Remove a deck entirely.

        Inputs:
            nocab_uuid: identity of the deck to remove. MUST already
                be stored.
        Output: none.
        Side effects: mutates this box's store inside a `with
            self._connection:` block, same as create() - see its
            docstring.
        Exceptions: raises KeyError if nocab_uuid isn't stored.

        Example:
            >>> box = DeckBox()
            >>> box.create(some_deck)
            >>> box.delete(some_deck.nocab_uuid)
        """
        existing = self.get_by_uuid(nocab_uuid)
        if existing is None:
            raise KeyError(f"delete: {nocab_uuid} is not stored")

        with self._connection:
            self._invalidate_metadata_if_needed(existing.source_game)
            self._delete_deck_row(nocab_uuid)
            self._delete_deck_cards_rows(nocab_uuid)

    def get_by_uuid(self, nocab_uuid: UUID) -> GenericDeck | None:
        """Look up a deck by this system's own identity.

        Inputs:
            nocab_uuid: identity to look up.
        Output: a freshly-constructed GenericDeck, or None if no deck
            has this nocab_uuid. Unlike the old in-memory
            implementation, no explicit copy is needed to protect
            against caller mutation - every returned object is built
            fresh from a row, never a reference into this box's own
            storage.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/mtg.db")])
            >>> box.get_by_uuid(some_uuid)
        """
        deck_row = self._fetch_deck_row(nocab_uuid)
        if deck_row is None:
            return None

        card_nocab_uuids = self._fetch_deck_cards(nocab_uuid)
        return self._row_to_deck(deck_row, card_nocab_uuids)

    def all_uuids(self, source_game: GameId | None = None) -> Iterator[UUID]:
        """Every nocab_uuid currently stored in this box.

        Inputs:
            source_game: if given, only uuids for decks in this game
                are yielded. None (default) yields every uuid this box
                holds, across every game it has loaded.
        Output: every matching nocab_uuid, in no particular guaranteed
            order, as a lazy generator - not a materialized list. This
            is the change that lets a read against a box far larger
            than memory actually work.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/mtg.db")])
            >>> for nocab_uuid in box.all_uuids(GameId.MTG):
            ...     ...
        """
        for row in self._stream_deck_rows(source_game):
            yield UUID(row["nocab_uuid"])

    def all_decks(self, source_game: GameId) -> Iterator[GenericDeck]:
        """Every deck currently stored in this box for one game.

        Inputs:
            source_game: which game's decks to enumerate.
        Output: every matching GenericDeck, in no particular guaranteed
            order, as a lazy generator - not a materialized list, same
            reasoning as all_uuids().
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/mtg.db")])
            >>> for deck in box.all_decks(GameId.MTG):
            ...     ...
        """
        for row in self._stream_deck_rows(source_game):
            nocab_uuid = UUID(row["nocab_uuid"])
            card_nocab_uuids = self._fetch_deck_cards(nocab_uuid)
            yield self._row_to_deck(row, card_nocab_uuids)

    def version_for(self, source_game: GameId) -> str:
        """A content hash over every currently-held source_game deck.

        Derived, not stored - mirrors CardBinder.version_for()'s
        reasoning. provenance is excluded for the same reason.

        Inputs:
            source_game: which game's decks to hash.
        Output: a sha256 hex digest (64 hex chars). A game with no
            decks yet still produces a fixed digest, not an error.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/gwent.db")])
            >>> box.version_for(GameId.GWENT)
            '7a91e0...'
        """
        digest = hashlib.sha256()

        # Stream every deck for source_game in nocab_uuid order, so
        # the hash reflects content only, never incidental row order -
        # same guarantee the old dict-based implementation got from
        # sorting an in-memory list, now from an ORDER BY instead.
        for deck in self._stream_decks_ordered_by_uuid(source_game):
            digest.update(self._hashable_deck_bytes(deck))
        return digest.hexdigest()

    def card_binder_version_for(self, source_game: GameId) -> str | None:
        """The CardBinder version this box's source_game decks were
        minted against, as recorded by save() and read back here.

        Inputs:
            source_game: which game's recorded version to read.
        Output: the version save() was given for source_game, or None
            if that game has never had a successful save() complete
            since this box connected to its current file (including:
            never loaded from a file carrying one, OR a prior run
            crashed after its first mutating write but before its own
            save() - see this class's docstring's crash-safety
            section). Callers checking staleness treat None the same
            as a real mismatch, not a free pass.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/gwent.db")])
            >>> box.card_binder_version_for(GameId.GWENT)
            '3f2b1c...'
        """
        row = self._fetch_metadata_row(source_game)
        return row["card_binder_version"] if row is not None else None

    def uuids_ranked_randomly(
        self, source_game: GameId, seed: int | None = None
    ) -> Iterator[tuple[UUID, int, int]]:
        """Rank every source_game deck by a one-time randomized order.

        Exists specifically so a caller (DeckBoxDealer) can assign an
        exact-ratio train/test/validation split without ever
        materializing this game's full uuid list in Python, or
        knowing this class's table/column names - the ranking runs
        entirely inside this connection. A plain read (no side
        effects), so it fits alongside all_uuids()/all_decks() rather
        than breaking this class's "just a store" framing.

        LOUD WARNING: SQLite's built-in RANDOM() is NOT seedable. This
        method's "randomized order" is built from a deterministic
        value computed from (seed, nocab_uuid), NOT from a bare
        ORDER BY RANDOM() - the latter would silently make the same
        seed produce a different ranking on every call. Do not
        "simplify" this to ORDER BY RANDOM() during implementation;
        that reintroduces exactly the non-reproducibility this method
        exists to avoid.

        Inputs:
            source_game: which game's decks to rank.
            seed: seed for the deterministic ordering. The same seed
                against the same box content always yields the same
                ranking. None means non-deterministic.
        Output: (nocab_uuid, rank, total) for every source_game deck,
            rank 1..total (dense, no ties), as a lazy generator. A game
            with no decks yields nothing.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/mtg.db")])
            >>> for nocab_uuid, rank, total in box.uuids_ranked_randomly(
            ...     GameId.MTG, seed=42
            ... ):
            ...     ...
        """
        self._register_seeded_order_function(seed)

        for row in self._stream_ranked_deck_rows(source_game):
            yield UUID(row["nocab_uuid"]), row["rank"], row["total"]

    # endregion CRUD by UUID

    # region Persistence

    @staticmethod
    def load(paths: list[Path]) -> "DeckBox":
        """Connect to, or merge, one or more per-game SQLite files.

        Three distinct cases - see this module's docstring's "load/save
        relationship" section for the reasoning behind each:
            - paths == []: a fresh ":memory:" box, not connected to any
              file. The sanctioned way to start a fresh, empty box.
            - len(paths) == 1: ALWAYS connects directly to that path,
              whether or not it exists yet. Every mutating call after
              this persists immediately - there is no in-memory
              accumulation to flush.
            - len(paths) >= 2: always merges into a FRESH ":memory:"
              connection. No given path is ever mutated - this is a
              genuine read. Last-path-wins on a nocab_uuid appearing in
              more than one given path (same rule for a game's
              card_binder_version_for() value).

        Inputs:
            paths: zero or more paths to data/final/decks/<game>.db-
                shaped files. Files for different games can be mixed
                in one call.
        Output: a DeckBox per the case above.
        Side effects: for len(paths) == 1, creates path's parent
            directory if missing and connects to (creating, if
            needed) that file directly. For 2+ paths, reads each given
            path; mutates none of them.
        Exceptions: raises if any given path exists but isn't a valid
            file for this schema.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/mtg.db")])
            >>> empty_box = DeckBox.load([])
        """
        if len(paths) == 0:
            return DeckBox()
        if len(paths) == 1:
            return DeckBox._connect_direct(paths[0])
        return DeckBox._merge_into_memory(paths)

    def save(self, path: Path, source_game: GameId, card_binder_version: str) -> None:
        """Ensure path holds this box's current source_game content,
        stamped with card_binder_version.

        Narrows to exactly two cases (see this module's docstring's
        "load/save relationship" section):
            - This box is already directly connected to path: every
              deck is already durable (see load()) - the only
              remaining work is the metadata upsert, which is what
              marks the box trustworthy again after being invalidated
              on this session's first write (see
              card_binder_version_for()'s docstring).
            - This box is still ":memory:", or connected to a
              different file: copy this box's full current state to
              path first, then the same metadata upsert.

        Inputs:
            path: destination file (e.g.
                data/final/decks/<game>.db).
            source_game: which game's subset of this box the caller
                considers current (informational for the metadata
                stamp - unlike the old JSONL implementation, save() no
                longer filters rows by source_game, since every deck
                is already durable by the time this is called for the
                direct-connect case).
            card_binder_version: the CardBinder version this box's
                source_game decks were minted against.
        Output: none.
        Side effects: creates path's parent directory if missing;
            if not already connected to path, copies this box's full
            state there; writes/overwrites the metadata row for
            source_game.
        Exceptions: raises on failure to write path.

        Example:
            >>> box.save(
            ...     Path("data/final/decks/mtg.db"),
            ...     GameId.MTG,
            ...     card_binder.version_for(GameId.MTG),
            ... )
        """
        if self._path == path:
            with self._connection:
                self._upsert_metadata_row(source_game, card_binder_version)
            return

        self._backup_to(path)
        # NOT self._upsert_metadata_row() - self is still connected to
        # its old state (":memory:" or a different file), not path, so
        # writing through self._connection would silently stamp the
        # wrong database. This stamps path's own copy directly.
        self._upsert_metadata_row_at(path, source_game, card_binder_version)

    @staticmethod
    def default_output_path(source_game: GameId) -> Path:
        """The conventional save() path for one game's deck box file.

        A recommended default, not an enforced requirement.

        Inputs:
            source_game: which game's conventional path to compute.
        Output: DEFAULT_OUTPUT_DIR / DEFAULT_OUTPUT_NAME, formatted
            with source_game (e.g. data/final/decks/mtg.db).
        Side effects: none - purely a path computation.
        Exceptions: none.

        Example:
            >>> DeckBox.default_output_path(GameId.MTG)
            PosixPath('data/final/decks/mtg.db')
        """
        return DeckBox.DEFAULT_OUTPUT_DIR / DeckBox.DEFAULT_OUTPUT_NAME.format(
            game=source_game.value
        )

    # endregion Persistence

    # region Private Helpers - schema and connection setup

    def _create_schema(self) -> None:
        """Create decks/deck_cards/metadata on self._connection if
        they don't already exist.

        Private helper - called by __init__ and by the two load()
        helpers below, on every fresh connection this class opens.
        Also where row_factory is set, since every connection this
        class ever opens goes through here exactly once.
        """
        self._connection.row_factory = sqlite3.Row
        self._connection.executescript(_SCHEMA_DDL)
        self._connection.commit()

    @staticmethod
    def _connect_direct(path: Path) -> "DeckBox":
        """Build a DeckBox directly connected to path, creating it
        (and its parent directory, and its schema) if it doesn't
        already exist.

        Private helper - single consumer is load()'s single-path case.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        box = DeckBox()
        box._connection.close()
        box._connection = sqlite3.connect(str(path))
        box._path = path
        box._create_schema()
        return box

    @staticmethod
    def _merge_into_memory(paths: list[Path]) -> "DeckBox":
        """Build a fresh ":memory:" DeckBox holding the union of every
        given path's decks and metadata, last-path-wins on a repeated
        nocab_uuid or source_game.

        Private helper - single consumer is load()'s multi-path case.
        Must never open a direct connection to (or otherwise mutate)
        any path in paths - see this class's docstring.
        """
        box = DeckBox()
        for path in paths:
            box._merge_path_into(path)
        return box

    def _merge_path_into(self, path: Path) -> None:
        """Read-only merge of one path's decks/deck_cards/metadata into
        this (already-open, typically ":memory:") connection.

        Private helper - single consumer is _merge_into_memory(). Never
        writes to path - ATTACHes it, SELECTs from it, DETACHes it.
        Last-path-wins: for a nocab_uuid this path also provides, its
        existing deck_cards rows (from an earlier-merged path) are
        cleared first, since a plain INSERT OR REPLACE into decks alone
        wouldn't remove card rows an earlier path had that this path's
        version doesn't.
        """
        self._connection.execute("ATTACH DATABASE ? AS merge_source", (str(path),))
        try:
            self._connection.execute(
                "DELETE FROM deck_cards WHERE deck_uuid IN "
                "(SELECT nocab_uuid FROM merge_source.decks)"
            )
            self._connection.execute(
                "INSERT OR REPLACE INTO decks SELECT * FROM merge_source.decks"
            )
            self._connection.execute(
                "INSERT INTO deck_cards SELECT * FROM merge_source.deck_cards"
            )
            self._connection.execute(
                "INSERT OR REPLACE INTO metadata SELECT * FROM merge_source.metadata"
            )
            self._connection.commit()
        finally:
            self._connection.execute("DETACH DATABASE merge_source")

    def _backup_to(self, path: Path) -> None:
        """Copy this box's full current database state onto path.

        Private helper - single consumer is save()'s not-yet-connected
        branch. Creates path's parent directory first.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        destination = sqlite3.connect(str(path))
        try:
            self._connection.backup(destination)
        finally:
            destination.close()

    # endregion Private Helpers - schema and connection setup

    # region Private Helpers - metadata / crash-safety

    def _invalidate_metadata_if_needed(self, source_game: GameId) -> None:
        """Clear source_game's metadata row unconditionally.

        Private helper - called at the top of every public mutating
        method's `with self._connection:` block (see create()'s
        docstring), before the row write(s) that follow it in the same
        block - see this class's docstring's crash-safety section for
        why. Deliberately unconditional, not "only if not already done
        this session": deleting an already-absent row is a cheap no-op,
        and a Python-side "already done" cache was tried and removed -
        it could desync from the SQL transaction's own commit/rollback
        (a rolled-back DELETE would still have marked the cache
        "already invalidated" in Python, silently skipping the real
        DELETE on a later retry within the same instance - exactly the
        stale-metadata bug this mechanism exists to prevent). The
        method name keeps "_if_needed" for its callers' sake (some rows
        genuinely won't exist to delete), not because of any internal
        caching.
        """
        self._connection.execute(
            "DELETE FROM metadata WHERE source_game = ?", (source_game.value,)
        )

    def _fetch_metadata_row(self, source_game: GameId) -> sqlite3.Row | None:
        """The raw metadata row for source_game, or None if absent.

        Private helper - single consumer is card_binder_version_for().
        """
        cursor = self._connection.execute(
            "SELECT * FROM metadata WHERE source_game = ?", (source_game.value,)
        )
        return cursor.fetchone()

    def _upsert_metadata_row(
        self, source_game: GameId, card_binder_version: str
    ) -> None:
        """Insert or overwrite source_game's metadata row on
        self._connection. NOT committed here - save() commits once,
        after this call returns.

        Private helper - single consumer is save()'s already-connected
        branch.
        """
        self._connection.execute(
            "INSERT OR REPLACE INTO metadata (source_game, card_binder_version) VALUES (?, ?)",
            (source_game.value, card_binder_version),
        )

    def _upsert_metadata_row_at(
        self, path: Path, source_game: GameId, card_binder_version: str
    ) -> None:
        """Insert or overwrite source_game's metadata row directly in
        path's own file, via a short-lived separate connection.

        Private helper - single consumer is save()'s not-yet-connected
        branch, where self._connection is NOT path's database (still
        ":memory:", or connected elsewhere) - the stamp has to land in
        the file _backup_to() just wrote, not in self's own connection.
        """
        connection = sqlite3.connect(str(path))
        try:
            connection.execute(
                "INSERT OR REPLACE INTO metadata (source_game, card_binder_version) VALUES (?, ?)",
                (source_game.value, card_binder_version),
            )
            connection.commit()
        finally:
            connection.close()

    # endregion Private Helpers - metadata / crash-safety

    # region Private Helpers - deck rows

    def _deck_row_exists(self, nocab_uuid: UUID) -> bool:
        """Whether nocab_uuid already has a row in decks.

        Private helper - single consumer is create().
        """
        cursor = self._connection.execute(
            "SELECT 1 FROM decks WHERE nocab_uuid = ?", (str(nocab_uuid),)
        )
        return cursor.fetchone() is not None

    def _fetch_deck_row(self, nocab_uuid: UUID) -> sqlite3.Row | None:
        """The raw decks row for nocab_uuid, or None if absent.

        Private helper - single consumer is get_by_uuid().
        """
        cursor = self._connection.execute(
            "SELECT * FROM decks WHERE nocab_uuid = ?", (str(nocab_uuid),)
        )
        return cursor.fetchone()

    def _fetch_deck_cards(self, nocab_uuid: UUID) -> list[UUID]:
        """nocab_uuid's card_nocab_uuids multiset, expanded from
        deck_cards' (card_uuid, count) rows back into a flat,
        duplicates-meaningful list.

        Private helper - consumers are get_by_uuid()/all_decks().
        """
        cursor = self._connection.execute(
            "SELECT card_uuid, count FROM deck_cards WHERE deck_uuid = ?",
            (str(nocab_uuid),),
        )
        card_nocab_uuids: list[UUID] = []
        for row in cursor.fetchall():
            card_nocab_uuids.extend([UUID(row["card_uuid"])] * row["count"])
        return card_nocab_uuids

    def _stream_deck_rows(self, source_game: GameId | None) -> Iterator[sqlite3.Row]:
        """Every decks row, filtered by source_game if given, in no
        particular guaranteed order, as a lazy generator.

        Private helper - consumers are all_uuids()/all_decks().
        """
        if source_game is None:
            cursor = self._connection.execute("SELECT * FROM decks")
        else:
            cursor = self._connection.execute(
                "SELECT * FROM decks WHERE source_game = ?", (source_game.value,)
            )
        yield from cursor

    def _stream_decks_ordered_by_uuid(
        self, source_game: GameId
    ) -> Iterator[GenericDeck]:
        """Every source_game GenericDeck, ordered by nocab_uuid, as a
        lazy generator.

        Private helper - single consumer is version_for().
        """
        cursor = self._connection.execute(
            "SELECT * FROM decks WHERE source_game = ? ORDER BY nocab_uuid",
            (source_game.value,),
        )
        for row in cursor:
            nocab_uuid = UUID(row["nocab_uuid"])
            card_nocab_uuids = self._fetch_deck_cards(nocab_uuid)
            yield self._row_to_deck(row, card_nocab_uuids)

    def _stream_ranked_deck_rows(self, source_game: GameId) -> Iterator[sqlite3.Row]:
        """Every source_game decks row, ranked 1..total by this
        connection's registered seeded-order function (see
        _register_seeded_order_function()), as a lazy generator - the
        ROW_NUMBER() OVER (...) + COUNT(*) OVER () query this whole
        method exists to run entirely inside SQLite.

        Private helper - single consumer is uuids_ranked_randomly().
        """
        cursor = self._connection.execute(
            f"""
            SELECT nocab_uuid,
                   ROW_NUMBER() OVER (ORDER BY {_SEEDED_ORDER_FUNCTION_NAME}(nocab_uuid)) AS rank,
                   COUNT(*) OVER () AS total
            FROM decks
            WHERE source_game = ?
            """,
            (source_game.value,),
        )
        yield from cursor

    def _register_seeded_order_function(self, seed: int | None) -> None:
        """Register a deterministic, seeded ordering function on this
        connection (via sqlite3.Connection.create_function()) for
        _stream_ranked_deck_rows() to sort by - NOT SQLite's own
        RANDOM(), which cannot be seeded. See
        uuids_ranked_randomly()'s docstring's loud warning.

        Private helper - single consumer is uuids_ranked_randomly().
        When seed is None, a fresh random value is generated once here
        (not per row) so this one call produces a single coherent
        random permutation, genuinely different across separate calls -
        "non-deterministic" per-call, not per-row noise within a call.
        """
        effective_seed = seed if seed is not None else secrets.token_hex(16)

        def seeded_order(nocab_uuid: str) -> str:
            return hashlib.sha256(f"{effective_seed}:{nocab_uuid}".encode()).hexdigest()

        self._connection.create_function(_SEEDED_ORDER_FUNCTION_NAME, 1, seeded_order)

    def _deck_row_values(self, deck: GenericDeck) -> tuple:
        """deck's own-row column values, in decks' column order -
        shared by _insert_deck_row()/_update_deck_row() so the two
        never drift apart on which columns exist.

        Private helper - consumers are _insert_deck_row()/_update_deck_row().
        """
        provenance = deck.provenance
        return (
            str(deck.nocab_uuid),
            deck.source_game.value,
            deck.name,
            provenance.data_source.value if provenance is not None else None,
            provenance.source_id if provenance is not None else None,
            provenance.fetched_at.isoformat() if provenance is not None else None,
        )

    def _insert_deck_row(self, deck: GenericDeck) -> None:
        """Insert deck's own row into decks (not its card_cards rows -
        see _insert_deck_cards_rows()). NOT committed here - the
        calling public method commits once, after every row it touches
        this call has been written (see create()'s docstring).

        Private helper - consumers are create()/create_if_absent().
        """
        self._connection.execute(
            """
            INSERT INTO decks (
                nocab_uuid, source_game, name,
                provenance_data_source, provenance_source_id, provenance_fetched_at
            ) VALUES (?, ?, ?, ?, ?, ?)
            """,
            self._deck_row_values(deck),
        )

    def _update_deck_row(self, deck: GenericDeck) -> None:
        """Overwrite an already-stored deck's own row in decks (not
        its deck_cards rows). NOT committed here - see
        _insert_deck_row()'s docstring.

        Private helper - consumers are update()/replace().
        """
        nocab_uuid, source_game, name, data_source, source_id, fetched_at = (
            self._deck_row_values(deck)
        )
        self._connection.execute(
            """
            UPDATE decks
            SET source_game = ?, name = ?,
                provenance_data_source = ?, provenance_source_id = ?, provenance_fetched_at = ?
            WHERE nocab_uuid = ?
            """,
            (source_game, name, data_source, source_id, fetched_at, nocab_uuid),
        )

    def _delete_deck_row(self, nocab_uuid: UUID) -> None:
        """Delete nocab_uuid's row from decks. NOT committed here - see
        _insert_deck_row()'s docstring.

        Private helper - single consumer is delete().
        """
        self._connection.execute(
            "DELETE FROM decks WHERE nocab_uuid = ?", (str(nocab_uuid),)
        )

    def _insert_deck_cards_rows(
        self, deck_uuid: UUID, card_nocab_uuids: list[UUID]
    ) -> None:
        """Insert deck_uuid's card_nocab_uuids multiset into
        deck_cards, collapsed to one (deck_uuid, card_uuid, count) row
        per distinct card. NOT committed here - see
        _insert_deck_row()'s docstring.

        Private helper - consumers are create()/create_if_absent().
        """
        counts = Counter(card_nocab_uuids)
        self._connection.executemany(
            "INSERT INTO deck_cards (deck_uuid, card_uuid, count) VALUES (?, ?, ?)",
            [
                (str(deck_uuid), str(card_uuid), count)
                for card_uuid, count in counts.items()
            ],
        )

    def _replace_deck_cards_rows(
        self, deck_uuid: UUID, card_nocab_uuids: list[UUID]
    ) -> None:
        """Replace deck_uuid's existing deck_cards rows wholesale with
        card_nocab_uuids' multiset.

        Private helper - consumers are update()/replace().
        """
        self._delete_deck_cards_rows(deck_uuid)
        self._insert_deck_cards_rows(deck_uuid, card_nocab_uuids)

    def _delete_deck_cards_rows(self, nocab_uuid: UUID) -> None:
        """Delete every deck_cards row for nocab_uuid. NOT committed
        here - see _insert_deck_row()'s docstring.

        Private helper - single consumer is delete().
        """
        self._connection.execute(
            "DELETE FROM deck_cards WHERE deck_uuid = ?", (str(nocab_uuid),)
        )

    def _row_to_deck(
        self, row: sqlite3.Row, card_nocab_uuids: list[UUID]
    ) -> GenericDeck:
        """Reconstruct a GenericDeck from a decks row plus its already-
        fetched card_nocab_uuids.

        Private helper - consumers are get_by_uuid()/all_decks().
        """
        provenance = None
        if row["provenance_data_source"] is not None:
            provenance = Provenance(
                data_source=DataSource(row["provenance_data_source"]),
                source_id=row["provenance_source_id"],
                fetched_at=datetime.fromisoformat(row["provenance_fetched_at"]),
            )
        return GenericDeck(
            nocab_uuid=UUID(row["nocab_uuid"]),
            source_game=GameId(row["source_game"]),
            name=row["name"],
            card_nocab_uuids=card_nocab_uuids,
            provenance=provenance,
        )

    def _hashable_deck_bytes(self, deck: GenericDeck) -> bytes:
        """deck's content, serialized for digest.update() - nocab_uuid/
        name/a SORTED card_nocab_uuids (a multiset, so incidental order
        must not affect the hash), provenance excluded.

        Private helper - single consumer is version_for().
        """
        return json.dumps(
            {
                "nocab_uuid": str(deck.nocab_uuid),
                "name": deck.name,
                "card_nocab_uuids": sorted(str(uuid) for uuid in deck.card_nocab_uuids),
            },
            sort_keys=True,
        ).encode("utf-8")

    # endregion Private Helpers - deck rows
