"""The multi-game deck store, backed by one SQLite file per game.

See plans/deckbox_sqlite.md for the design, and
src/data_refinement/card_binder/card_binder.py for the sibling this is
modeled on. DeckBox mirrors CardBinder's CRUD-by-uuid shape
only - it has NO AliasLedger and NO identity-collision handling of any
kind, because decks don't have the problem CardBinder's non-trivial
half exists to solve (see this container's README).

SQLite rather than an in-memory dict, so a box can hold far more decks
than fit in RAM (seventeenlands_game_data alone is ~15-20M decks).
Row-level SQL lives in _deck_tables.py; this class decides what to
write and when to commit.

THE LOAD/SAVE RELATIONSHIP, precisely (see load()/save()'s own
docstrings for the authoritative statement):
    - DeckBox() / load([]): a fresh ":memory:" connection, no path
      association.
    - load([one_path]): ALWAYS connects directly to one_path, whether
      or not it exists yet, so even a brand-new source's first
      ingestion is durable up to its last committed batch (see
      BATCHED COMMITS below). There is no separate in-memory copy to
      write out.
    - load([2+ paths]): always a fresh ":memory:" merge. No given path
      is ever mutated - this is a genuine read, unlike the single-path
      case above.

BATCHED COMMITS: every mutating call (create/create_if_absent/update/
replace/delete) runs its row write(s) - its own deck row, its
deck_cards rows, and its metadata invalidation - inside one SAVEPOINT,
nested in this box's open batch transaction (_batched_write()). A call
whose writes raise rolls back to its savepoint: that call leaves no
trace, and earlier calls in the same batch are kept. The batch
transaction commits after every commit_batch_size calls that wrote
(a rejected create(), a failed call, or a create_if_absent()
recurrence doesn't count), and on flush()/save(). A commit costs one
fsync on a file-backed box, so committing per call held
seventeenlands_game_data to ~75 decks/s. A process killed mid-batch
loses that whole uncommitted batch (SQLite rolls back its journal on
the next open) and never keeps half of one call. A caller that writes
through a single-path box must end with save() or flush(); decks
still pending when the connection closes are rolled back, and other
connections see no pending write until it commits. A large batch can
outgrow SQLite's page cache and take the file's exclusive lock before
its commit, so other connections reading the same file mid-run may
get "database is locked".

Two failures are batch-wide rather than per-call, and every mutating
call can raise them:
    - sqlite3.Error from the batch commit itself, raised by the call
      that filled the batch after its own writes succeeded. If the
      transaction survives, those writes commit with the next batch.
    - DeckBatchLostError: SQLite discarded the whole open transaction
      on its own (e.g. disk full, I/O error), taking every earlier
      pending call with it. It deliberately isn't a sqlite3.Error, so
      a caller that catches per-row sqlite3.Error and carries on can't
      swallow it and later save() a box missing those decks.

CRASH-SAFETY OF THE VERSION STAMP: because a single-path box persists
each batch as it commits, a run that crashes partway through
updating an EXISTING box must not leave metadata.card_binder_version
claiming a version that no longer accurately describes every row. Every
mutating call touching a given source_game clears (deletes) that game's
metadata row, inside the same savepoint as the row write(s) that follow
it (unconditionally - deleting an already-absent row is a cheap no-op,
and a Python-side "already done" cache could desync from a rolled-back
savepoint). So a committed deck change is always committed together
with its stamp's deletion. A pure-read session never touches metadata.
A crash - or a caught, retried exception - mid-run therefore leaves
metadata ABSENT for that game rather than falsely matching a stale
version - card_binder_version_for() returning None for an absent row
is the existing, documented contract, and existing callers already
treat None as untrustworthy (see e.g.
src/dojos/contrastive/dojo.py's ContrastiveDojo._check_deck_box_version()).
save() re-establishes the row only once a run completes without error.

THIS MAKES IDEMPOTENT-RETRY A LOAD-BEARING ASSUMPTION, not just a nice
property: a crash-then-retry only converges to correct final content
because every current DeckExtractionStage derives a deterministic
identity and does get_by_uuid()-then-create()-or-update() (see
extraction.py's own docstring). A hypothetical future stage using
create() with a fresh, non-deterministic uuid per row would silently
duplicate content on any crash+retry under this direct-connect model.

A nocab_uuid, once minted for a deck, is never regenerated by anything
in this file - a save()/load() round-trip returns the exact same uuid
for the exact same deck, always.
"""

import hashlib
import json
import sqlite3
from contextlib import contextmanager
from dataclasses import replace
from pathlib import Path
from typing import ClassVar, Iterator
from uuid import UUID

from src.data_refinement.deck_box._deck_tables import (
    DeckTables,
    deck_from_row,
    stamp_metadata_at,
)
from src.schema.card import GenericDeck, Provenance
from src.schema.game_id import GameId

# The one savepoint name every mutating call uses (see the module
# docstring's BATCHED COMMITS section). Calls never nest, so one fixed
# name is enough.
_WRITE_SAVEPOINT = "deck_write"


class DeckBatchLostError(RuntimeError):
    """SQLite discarded a DeckBox's whole pending batch, not just one call.

    See the module docstring's BATCHED COMMITS section for why this is
    not a sqlite3.Error.
    """


class DeckBox:
    """Multi-game deck store, backed by one SQLite file per game.

    Single-consumer-per-instance is not the right frame here - this is
    the shared, generic storage capability every deck_box extraction
    stage (and, eventually, training) reads from and writes into.
    Construction is always empty and unconnected to any file; load()
    is the sole entry point that connects a box to real, persisted
    content.
    """

    DEFAULT_OUTPUT_DIR: ClassVar[Path] = Path("data/final/decks")
    DEFAULT_OUTPUT_NAME: ClassVar[str] = "{game}.db"
    # Mutating calls per commit (see the module docstring's BATCHED
    # COMMITS section). At ~13 ms per fsync, 1,000 brings the commit
    # cost to ~0.01 ms a deck, below the row inserts and the raw-file
    # parsing around them, so a larger batch would gain little and only
    # grow the work a crash throws away.
    DEFAULT_COMMIT_BATCH_SIZE: ClassVar[int] = 1_000

    def __init__(self, commit_batch_size: int = DEFAULT_COMMIT_BATCH_SIZE) -> None:
        """Construct an empty deck box, backed by an in-memory SQLite database.

        Prefer load([]) over calling this directly when the intent is
        "start empty for an extraction run" - this constructor exists
        because load() is itself built on top of it.

        Inputs:
            commit_batch_size: mutating calls per commit (see the
                module docstring's BATCHED COMMITS section). Must be
                at least 1; 1 commits every call on its own.
        Output: none (constructor).
        Side effects: opens a fresh ":memory:" SQLite connection and
            creates this box's schema (decks/deck_cards/metadata) on
            it.
        Exceptions: raises ValueError if commit_batch_size < 1.
        """
        if commit_batch_size < 1:
            raise ValueError(
                f"DeckBox: commit_batch_size must be >= 1, got {commit_batch_size}"
            )
        self._connection = sqlite3.connect(":memory:")
        self._tables = DeckTables(self._connection)
        # None means "not connected to any real file" (see this
        # class's docstring's load/save relationship) - save()'s
        # narrow-vs-copy branch keys off this.
        self._path: Path | None = None
        self._commit_batch_size = commit_batch_size
        # Mutating calls since the last commit; flush() resets it.
        self._pending_writes = 0
        self._tables.create_schema()

    # region CRUD by UUID

    def create(self, deck: GenericDeck) -> GenericDeck:
        """Insert a brand-new deck.

        Callers (DeckExtractionStage implementations) are expected to
        have already determined that deck.nocab_uuid is genuinely new
        - this method exists to catch the mistake of calling it twice
        for the same uuid, not to perform that determination itself.

        Inputs:
            deck: the deck to insert. deck.nocab_uuid MUST NOT already
                be stored.
        Output: deck, unchanged (returned for symmetry with
            update()/replace(), which do return a possibly-different
            object).
        Side effects: mutates this box's store inside one
            _batched_write() savepoint - deck's own row, its deck_cards
            rows, and clearing deck.source_game's metadata row are
            kept together, or all rolled back together if this call
            raises partway through; they become durable with this
            call's batch (see the module docstring's BATCHED COMMITS
            section) - never a half-written row. May commit the
            pending batch. The duplicate-uuid check happens BEFORE the
            savepoint: a rejected (raising) call never opens it and
            leaves the store untouched.
        Exceptions: raises ValueError if deck.nocab_uuid is already
            stored - use update() or replace() instead.
            Also raises the batch-wide errors in the module
            docstring's BATCHED COMMITS section (sqlite3.Error,
            DeckBatchLostError).

        Example:
            >>> box = DeckBox()
            >>> box.create(some_deck)
        """
        # A duplicate create() is a caller mistake, not a legitimate
        # case - create_if_absent() exists for the "recurrence is
        # fine" case instead. Checked BEFORE invalidating metadata: a
        # rejected call never writes, so it must not pay the cost of
        # clearing the version stamp either.
        if self._tables.deck_exists(deck.nocab_uuid):
            raise ValueError(f"create: {deck.nocab_uuid} is already stored")

        with self._batched_write():
            self._tables.clear_metadata(deck.source_game)
            self._tables.insert_deck_row(deck)
            self._tables.insert_deck_cards(deck.nocab_uuid, deck.card_nocab_uuids)
        return deck

    def create_if_absent(self, deck: GenericDeck) -> GenericDeck:
        """Insert deck only if deck.nocab_uuid isn't already stored.

        The counterpart to create() for callers whose id scheme is
        deliberately content-derived and therefore expect the same id
        to legitimately recur across many calls. On a recurrence,
        deck is NOT compared against the stored value for equality -
        the existing entry wins unconditionally.

        Inputs:
            deck: the deck to insert if deck.nocab_uuid is new.
        Output: the deck now stored under deck.nocab_uuid - deck
            itself on a genuinely new id, or whatever was already
            stored on a recurrence.
        Side effects: mutates this box's store only when
            deck.nocab_uuid is new, inside a _batched_write()
            savepoint (see create()'s docstring) that also clears
            deck.source_game's metadata row if needed - a recurrence is
            the expected, non-error path
            here and must not pay that cost.
        Exceptions: none on a recurrence. On a new id, the
            batch-wide errors in the module docstring's BATCHED
            COMMITS section (sqlite3.Error, DeckBatchLostError).

        Example:
            >>> box = DeckBox()
            >>> box.create_if_absent(some_deck)
            >>> box.create_if_absent(some_deck)  # no-op, same id
        """
        existing = self.get_by_uuid(deck.nocab_uuid)
        if existing is not None:
            return existing

        with self._batched_write():
            self._tables.clear_metadata(deck.source_game)
            self._tables.insert_deck_row(deck)
            self._tables.insert_deck_cards(deck.nocab_uuid, deck.card_nocab_uuids)
        return deck

    def update(
        self,
        nocab_uuid: UUID,
        card_nocab_uuids: list[UUID] | None = None,
        name: str | None = None,
        provenance: Provenance | None = None,
    ) -> GenericDeck:
        """Selectively overwrite fields of an already-stored deck.

        "Update" here means "overwrite whichever of
        card_nocab_uuids/name/provenance are given (not None), leave
        the rest untouched" - the closest equivalent for a dataclass
        with only scalar/list fields. This is the "leave other fields
        alone" counterpart to replace()'s full swap.

        Inputs:
            nocab_uuid: identity of the deck to update. MUST already
                be stored.
            card_nocab_uuids: new full list of card nocab_uuids
                (unordered, duplicates meaningful), or None (default)
                to leave unchanged. REPLACES the existing list wholesale.
            name: new name, or None (default) to leave unchanged.
            provenance: new provenance, or None (default) to leave
                unchanged.
        Output: the updated GenericDeck as now stored.
        Side effects: mutates this box's store inside a
            _batched_write() savepoint, same as create() - see its
            docstring.
        Exceptions: raises KeyError if nocab_uuid isn't stored.
            Also raises the batch-wide errors in the module
            docstring's BATCHED COMMITS section (sqlite3.Error,
            DeckBatchLostError).

        Example:
            >>> box = DeckBox()
            >>> box.create(some_deck)
            >>> box.update(some_deck.nocab_uuid, name="Renamed Deck")
        """
        existing = self.get_by_uuid(nocab_uuid)
        if existing is None:
            raise KeyError(f"update: {nocab_uuid} is not stored")

        updated = replace(
            existing,
            card_nocab_uuids=(
                card_nocab_uuids
                if card_nocab_uuids is not None
                else existing.card_nocab_uuids
            ),
            name=name if name is not None else existing.name,
            provenance=(provenance if provenance is not None else existing.provenance),
        )

        with self._batched_write():
            self._tables.clear_metadata(existing.source_game)
            self._tables.update_deck_row(updated)
            if card_nocab_uuids is not None:
                self._tables.replace_deck_cards(nocab_uuid, card_nocab_uuids)
        return updated

    def replace(self, nocab_uuid: UUID, deck: GenericDeck) -> GenericDeck:
        """Fully overwrite an already-stored deck's content.

        Every field of deck becomes the stored value for nocab_uuid -
        conceptually a delete-then-add, except nocab_uuid itself never
        changes.

        Inputs:
            nocab_uuid: identity of the deck to replace. MUST already
                be stored.
            deck: the new full deck content. deck.nocab_uuid MUST
                equal nocab_uuid.
        Output: deck, unchanged.
        Side effects: mutates this box's store inside a
            _batched_write() savepoint, same as create() - see its
            docstring.
        Exceptions: raises KeyError if nocab_uuid isn't stored. Raises
            ValueError if deck.nocab_uuid != nocab_uuid.
            Also raises the batch-wide errors in the module
            docstring's BATCHED COMMITS section (sqlite3.Error,
            DeckBatchLostError).

        Example:
            >>> box = DeckBox()
            >>> box.create(some_deck)
            >>> box.replace(some_deck.nocab_uuid, updated_deck)
        """
        if deck.nocab_uuid != nocab_uuid:
            raise ValueError(
                f"replace: deck.nocab_uuid ({deck.nocab_uuid}) != target uuid ({nocab_uuid})"
            )
        existing = self.get_by_uuid(nocab_uuid)
        if existing is None:
            raise KeyError(f"replace: {nocab_uuid} is not stored")

        with self._batched_write():
            self._tables.clear_metadata(deck.source_game)
            self._tables.update_deck_row(deck)
            self._tables.replace_deck_cards(nocab_uuid, deck.card_nocab_uuids)
        return deck

    def delete(self, nocab_uuid: UUID) -> None:
        """Remove a deck entirely.

        Inputs:
            nocab_uuid: identity of the deck to remove. MUST already
                be stored.
        Output: none.
        Side effects: mutates this box's store inside a
            _batched_write() savepoint, same as create() - see its
            docstring.
        Exceptions: raises KeyError if nocab_uuid isn't stored.
            Also raises the batch-wide errors in the module
            docstring's BATCHED COMMITS section (sqlite3.Error,
            DeckBatchLostError).

        Example:
            >>> box = DeckBox()
            >>> box.create(some_deck)
            >>> box.delete(some_deck.nocab_uuid)
        """
        existing = self.get_by_uuid(nocab_uuid)
        if existing is None:
            raise KeyError(f"delete: {nocab_uuid} is not stored")

        with self._batched_write():
            self._tables.clear_metadata(existing.source_game)
            self._tables.delete_deck_row(nocab_uuid)
            self._tables.delete_deck_cards(nocab_uuid)

    def get_by_uuid(self, nocab_uuid: UUID) -> GenericDeck | None:
        """Look up a deck by this system's own identity.

        Inputs:
            nocab_uuid: identity to look up.
        Output: a freshly-constructed GenericDeck, or None if no deck
            has this nocab_uuid. Every returned object is built fresh
            from a row, never a reference into this box's own storage,
            so callers may mutate it freely.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/mtg.db")])
            >>> box.get_by_uuid(some_uuid)
        """
        deck_row = self._tables.deck_row(nocab_uuid)
        if deck_row is None:
            return None
        return deck_from_row(deck_row, self._tables.deck_cards(nocab_uuid))

    def all_uuids(self, source_game: GameId | None = None) -> Iterator[UUID]:
        """Every nocab_uuid currently stored in this box.

        Inputs:
            source_game: if given, only uuids for decks in this game
                are yielded. None (default) yields every uuid this box
                holds, across every game it has loaded.
        Output: every matching nocab_uuid, in no particular guaranteed
            order, as a lazy generator - not a materialized list, so a
            box far larger than memory can still be read.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/mtg.db")])
            >>> for nocab_uuid in box.all_uuids(GameId.MTG):
            ...     ...
        """
        for row in self._tables.deck_rows(source_game):
            yield UUID(row["nocab_uuid"])

    def all_decks(self, source_game: GameId) -> Iterator[GenericDeck]:
        """Every deck currently stored in this box for one game.

        Inputs:
            source_game: which game's decks to enumerate.
        Output: every matching GenericDeck, in no particular guaranteed
            order, as a lazy generator - not a materialized list, same
            reasoning as all_uuids().
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/mtg.db")])
            >>> for deck in box.all_decks(GameId.MTG):
            ...     ...
        """
        yield from self._decks_from_rows(self._tables.deck_rows(source_game))

    def version_for(self, source_game: GameId) -> str:
        """A content hash over every currently-held source_game deck.

        Derived, not stored - mirrors CardBinder.version_for()'s
        reasoning. provenance is excluded for the same reason.

        Inputs:
            source_game: which game's decks to hash.
        Output: a sha256 hex digest (64 hex chars). A game with no
            decks yet still produces a fixed digest, not an error.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/gwent.db")])
            >>> box.version_for(GameId.GWENT)
            '7a91e0...'
        """
        digest = hashlib.sha256()

        # nocab_uuid order, so the hash reflects content only, never
        # incidental row order.
        ordered_rows = self._tables.deck_rows(source_game, ordered_by_uuid=True)
        for deck in self._decks_from_rows(ordered_rows):
            digest.update(_hashable_deck_bytes(deck))
        return digest.hexdigest()

    def card_binder_version_for(self, source_game: GameId) -> str | None:
        """The CardBinder version this box's source_game decks were
        minted against, as recorded by save() and read back here.

        Inputs:
            source_game: which game's recorded version to read.
        Output: the version save() was given for source_game, or None
            if that game has never had a successful save() complete
            since this box connected to its current file (including:
            never loaded from a file carrying one, OR a prior run
            crashed after its first mutating write but before its own
            save() - see this class's docstring's crash-safety
            section). Callers checking staleness treat None the same
            as a real mismatch, not a free pass.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/gwent.db")])
            >>> box.card_binder_version_for(GameId.GWENT)
            '3f2b1c...'
        """
        row = self._tables.metadata_row(source_game)
        return row["card_binder_version"] if row is not None else None

    def uuids_ranked_randomly(
        self, source_game: GameId, seed: int | None = None
    ) -> Iterator[tuple[UUID, int, int]]:
        """Rank every source_game deck by a one-time randomized order.

        Exists specifically so a caller (DeckBoxDealer) can assign an
        exact-ratio train/test/validation split without ever
        materializing this game's full uuid list in Python, or
        knowing this class's table/column names - the ranking runs
        entirely inside this connection. A plain read (no side
        effects), so it fits alongside all_uuids()/all_decks() rather
        than breaking this class's "just a store" framing.

        LOUD WARNING: SQLite's built-in RANDOM() is NOT seedable. This
        method's "randomized order" is built from a deterministic
        value computed from (seed, nocab_uuid), NOT from a bare
        ORDER BY RANDOM() - the latter would silently make the same
        seed produce a different ranking on every call. Do not
        "simplify" this to ORDER BY RANDOM() during implementation;
        that reintroduces exactly the non-reproducibility this method
        exists to avoid.

        Inputs:
            source_game: which game's decks to rank.
            seed: seed for the deterministic ordering. The same seed
                against the same box content always yields the same
                ranking. None means non-deterministic.
        Output: (nocab_uuid, rank, total) for every source_game deck,
            rank 1..total (dense, no ties), as a lazy generator. A game
            with no decks yields nothing.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/mtg.db")])
            >>> for nocab_uuid, rank, total in box.uuids_ranked_randomly(
            ...     GameId.MTG, seed=42
            ... ):
            ...     ...
        """
        for row in self._tables.ranked_deck_rows(source_game, seed):
            yield UUID(row["nocab_uuid"]), row["rank"], row["total"]

    # endregion CRUD by UUID

    # region Persistence

    @staticmethod
    def load(
        paths: list[Path], commit_batch_size: int = DEFAULT_COMMIT_BATCH_SIZE
    ) -> "DeckBox":
        """Connect to, or merge, one or more per-game SQLite files.

        Three distinct cases - see this module's docstring's "load/save
        relationship" section for the reasoning behind each:
            - paths == []: a fresh ":memory:" box, not connected to any
              file. The sanctioned way to start a fresh, empty box.
            - len(paths) == 1: ALWAYS connects directly to that path,
              whether or not it exists yet. Mutating calls after this
              persist batch by batch (see the module docstring's
              BATCHED COMMITS section); end with save() or flush().
            - len(paths) >= 2: always merges into a FRESH ":memory:"
              connection. No given path is ever mutated - this is a
              genuine read. Last-path-wins on a nocab_uuid appearing in
              more than one given path (same rule for a game's
              card_binder_version_for() value).

        Inputs:
            paths: zero or more paths to data/final/decks/<game>.db-
                shaped files. Files for different games can be mixed
                in one call.
            commit_batch_size: mutating calls per commit on the
                returned box (see DeckBox.__init__()).
        Output: a DeckBox per the case above.
        Side effects: for len(paths) == 1, creates path's parent
            directory if missing and connects to (creating, if
            needed) that file directly. For 2+ paths, reads each given
            path; mutates none of them.
        Exceptions: raises if any given path exists but isn't a valid
            file for this schema. Raises ValueError if
            commit_batch_size < 1.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/mtg.db")])
            >>> empty_box = DeckBox.load([])
        """
        if len(paths) == 0:
            return DeckBox(commit_batch_size)
        if len(paths) == 1:
            return DeckBox._connect_direct(paths[0], commit_batch_size)
        return DeckBox._merge_into_memory(paths, commit_batch_size)

    def save(self, path: Path, source_game: GameId, card_binder_version: str) -> None:
        """Ensure path holds this box's current source_game content,
        stamped with card_binder_version.

        Narrows to exactly two cases (see this module's docstring's
        "load/save relationship" section):
            - This box is already directly connected to path: once
              the pending batch is committed, every deck is durable
              (see load()) - the only remaining work is the metadata
              upsert, which is what
              marks the box trustworthy again after being invalidated
              on this session's first write (see
              card_binder_version_for()'s docstring).
            - This box is still ":memory:", or connected to a
              different file: copy this box's full current state to
              path first, then the same metadata upsert.

        Inputs:
            path: destination file (e.g.
                data/final/decks/<game>.db).
            source_game: which game's subset of this box the caller
                considers current (informational for the metadata
                stamp - save() does not filter rows by source_game).
            card_binder_version: the CardBinder version this box's
                source_game decks were minted against.
        Output: none.
        Side effects: commits this box's pending batch (flush());
            creates path's parent directory if missing; if not already
            connected to path, copies this box's full state there;
            writes/overwrites the metadata row for source_game.
        Exceptions: raises on failure to write path.

        Example:
            >>> box.save(
            ...     Path("data/final/decks/mtg.db"),
            ...     GameId.MTG,
            ...     card_binder.version_for(GameId.MTG),
            ... )
        """
        # First, so the stamp below never lands before the decks it
        # vouches for, and _backup_to() copies committed state only.
        self.flush()
        if self._path == path:
            with self._connection:
                self._tables.upsert_metadata(source_game, card_binder_version)
            return

        self._backup_to(path)
        # NOT self._tables - self is still connected to its old state
        # (":memory:" or a different file), not path, so writing through
        # self._connection would silently stamp the wrong database.
        stamp_metadata_at(path, source_game, card_binder_version)

    def flush(self) -> None:
        """Commit every mutating call still pending in this box's batch.

        save() calls this itself. Call it directly only when a box
        written through a single-path load() is abandoned without a
        save(), or when another connection must see the writes so far
        (see the module docstring's BATCHED COMMITS section).

        Inputs: none.
        Output: none.
        Side effects: commits the open batch transaction, if any.
        Exceptions: raises sqlite3.Error if the commit fails.

        Example:
            >>> box = DeckBox.load([Path("data/final/decks/mtg.db")])
            >>> box.create(some_deck)
            >>> box.flush()  # now visible to other connections
        """
        if self._connection.in_transaction:
            self._connection.commit()
        self._pending_writes = 0

    @staticmethod
    def default_output_path(source_game: GameId) -> Path:
        """The conventional save() path for one game's deck box file.

        A recommended default, not an enforced requirement.

        Inputs:
            source_game: which game's conventional path to compute.
        Output: DEFAULT_OUTPUT_DIR / DEFAULT_OUTPUT_NAME, formatted
            with source_game (e.g. data/final/decks/mtg.db).
        Side effects: none - purely a path computation.
        Exceptions: none.

        Example:
            >>> DeckBox.default_output_path(GameId.MTG)
            PosixPath('data/final/decks/mtg.db')
        """
        return DeckBox.DEFAULT_OUTPUT_DIR / DeckBox.DEFAULT_OUTPUT_NAME.format(
            game=source_game.value
        )

    # endregion Persistence

    # region Private Helpers

    @contextmanager
    def _batched_write(self) -> Iterator[None]:
        """Run one mutating call's writes inside a savepoint in the open batch.

        Private helper - consumers are the five mutating CRUD methods.
        See the module docstring's BATCHED COMMITS section. The batch
        transaction is opened explicitly first: a SAVEPOINT that opens
        a transaction itself would commit it on RELEASE, which is the
        per-call commit this exists to avoid.

        Inputs: none.
        Output (yielded): none.
        Side effects: opens the batch transaction if none is open;
            releases the savepoint on a clean exit, or rolls back to
            it on an exception; commits the batch (flush()) once
            commit_batch_size calls are pending.
        Exceptions: re-raises whatever the wrapped writes raise, after
            rolling them back. Raises DeckBatchLostError (chained from
            the original error) if SQLite already rolled back the whole
            transaction. Whatever flush() raises propagates.
        """
        if not self._connection.in_transaction:
            self._connection.execute("BEGIN")
        self._connection.execute(f"SAVEPOINT {_WRITE_SAVEPOINT}")
        try:
            yield
        except BaseException as error:
            if not self._connection.in_transaction:
                # SQLite rolled back the whole batch itself; the
                # savepoint is gone with it, and so are this batch's
                # earlier calls.
                lost_writes = self._pending_writes
                self._pending_writes = 0
                raise DeckBatchLostError(
                    f"SQLite discarded the open batch ({lost_writes} earlier "
                    "call(s) plus this one); re-run the extraction"
                ) from error
            self._connection.execute(f"ROLLBACK TO {_WRITE_SAVEPOINT}")
            self._connection.execute(f"RELEASE {_WRITE_SAVEPOINT}")
            raise
        self._connection.execute(f"RELEASE {_WRITE_SAVEPOINT}")
        self._pending_writes += 1
        if self._pending_writes >= self._commit_batch_size:
            self.flush()

    @staticmethod
    def _connect_direct(path: Path, commit_batch_size: int) -> "DeckBox":
        """Build a DeckBox directly connected to path, creating it
        (and its parent directory, and its schema) if it doesn't
        already exist.

        Private helper - single consumer is load()'s single-path case.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        box = DeckBox(commit_batch_size)
        box._connection.close()
        box._connection = sqlite3.connect(str(path))
        box._tables = DeckTables(box._connection)
        box._path = path
        box._tables.create_schema()
        return box

    @staticmethod
    def _merge_into_memory(paths: list[Path], commit_batch_size: int) -> "DeckBox":
        """Build a fresh ":memory:" DeckBox holding the union of every
        given path's decks and metadata, last-path-wins on a repeated
        nocab_uuid or source_game.

        Private helper - single consumer is load()'s multi-path case.
        Never mutates any path in paths (see DeckTables.merge_from()).
        """
        box = DeckBox(commit_batch_size)
        for path in paths:
            box._tables.merge_from(path)
        return box

    def _backup_to(self, path: Path) -> None:
        """Copy this box's full current database state onto path.

        Private helper - single consumer is save()'s not-yet-connected
        branch. Creates path's parent directory first.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        destination = sqlite3.connect(str(path))
        try:
            self._connection.backup(destination)
        finally:
            destination.close()

    def _decks_from_rows(self, rows: Iterator[sqlite3.Row]) -> Iterator[GenericDeck]:
        """Each decks row joined with its deck_cards, as GenericDecks.

        Private helper - consumers are all_decks()/version_for().
        """
        for row in rows:
            card_nocab_uuids = self._tables.deck_cards(UUID(row["nocab_uuid"]))
            yield deck_from_row(row, card_nocab_uuids)

    # endregion Private Helpers


def _hashable_deck_bytes(deck: GenericDeck) -> bytes:
    """deck's content, serialized for digest.update() - nocab_uuid/
    name/a SORTED card_nocab_uuids (a multiset, so incidental order
    must not affect the hash), provenance excluded.

    Private helper - single consumer is DeckBox.version_for().
    """
    return json.dumps(
        {
            "nocab_uuid": str(deck.nocab_uuid),
            "name": deck.name,
            "card_nocab_uuids": sorted(str(uuid) for uuid in deck.card_nocab_uuids),
        },
        sort_keys=True,
    ).encode("utf-8")
