"""Frozen leader-name label vocabulary for gwent leader-classification
metrics (e.g. LeaderMaskedFromDeckMetric).

FRESHNESS: generated by leader_deck_counts.count_decks_per_leader()
against data/raw/play_gwent/guides.jsonl on 2026-09-09 — exactly 42
distinct leader names appeared across all 60,138 guide decks, each
with a substantial sample (min 491, max 2555 decks per leader; no
long tail of rare leaders). This is a frozen snapshot, not a live
derivation — a future gwent.one/playgwent.com expansion adding a new
leader will silently be absent from LEADER_NAMES until this list is
regenerated by re-running count_decks_per_leader() and diffing its
keys against this tuple.

'Doulbe Cross' (entry below) is not a typo introduced here — it is
the literal spelling playgwent.com's own guide data uses for that
leader's name (should read "Double Cross"). Kept verbatim since this
tuple's job is to match the raw corpus's actual label values, not to
correct them.
"""

LEADER_NAMES: tuple[str, ...] = (
    "Arachas Swarm",
    "Battle Trance",
    "Blaze of Glory",
    "Blood Money",
    "Blood Scent",
    "Call of Harmony",
    "Carapace",
    "Congregate",
    "Deadeye Ambush",
    "Doulbe Cross",
    "Enslave",
    "Force of Nature",
    "Fruits of Ysgith",
    "Guerilla Tactics",
    "Hidden Cache",
    "Imperial Formation",
    "Imposter",
    "Imprisonment",
    "Inspired Zeal",
    "Invigorate",
    "Jackpot",
    "Lined Pockets",
    "Mahakam Forge",
    "Mobilization",
    "Nature's Gift",
    "Off the Books",
    "Onslaught",
    "Overwhelming Hunger",
    "Patricidal Fury",
    "Pincer Maneuver",
    "Pirate's Cove",
    "Precision Strike",
    "Rage of the Sea",
    "Reckless Fury",
    "Royal Inspiration",
    "Shieldwall",
    "Stockpile",
    "Tactical Decision",
    "Toussaintois Hospitality",
    "Uprising",
    "Ursine Ritual",
    "White Frost",
)
