"""Frozen leader-name label vocabulary for gwent leader-classification
metrics (e.g. LeaderMaskedFromDeckMetric).

FRESHNESS: generated by leader_deck_counts.count_decks_per_leader()
against data/final/cards/gwent.jsonl + data/raw/play_gwent/guides.jsonl
on 2026-09-25 — exactly 42 distinct leaders (by gwent.one CardBinder
canonical name, the same name LeaderMaskedFromDeckMetric._label_for_card
checks against) appeared across 60,197 guide decks whose "leaderId"
resolved, each with a substantial sample (min 492, max 2559 decks per
leader; no long tail of rare leaders). This is a frozen snapshot, not a
live derivation — a future gwent.one/playgwent.com expansion adding a
new leader will silently be absent from LEADER_NAMES until this list is
regenerated by re-running count_decks_per_leader() and diffing its keys
against this tuple.

An earlier version of this file (built by counting playgwent.com's raw
guide text "leader"."name" instead of the gwent.one CardBinder's
canonical name) carried "Doulbe Cross" and "Reckless Fury" — spellings
that matched playgwent.com's own guide text but not gwent.one's card
names, so LeaderMaskedFromDeckMetric (which checks the latter) silently
fell back every one of those decks to OTHER. Regenerating against the
CardBinder name fixed this to "Double Cross" and "Reckless Flurry".
"""

LEADER_NAMES: tuple[str, ...] = (
    "Arachas Swarm",
    "Battle Trance",
    "Blaze of Glory",
    "Blood Money",
    "Blood Scent",
    "Call of Harmony",
    "Carapace",
    "Congregate",
    "Deadeye Ambush",
    "Double Cross",
    "Enslave",
    "Force of Nature",
    "Fruits of Ysgith",
    "Guerilla Tactics",
    "Hidden Cache",
    "Imperial Formation",
    "Imposter",
    "Imprisonment",
    "Inspired Zeal",
    "Invigorate",
    "Jackpot",
    "Lined Pockets",
    "Mahakam Forge",
    "Mobilization",
    "Nature's Gift",
    "Off the Books",
    "Onslaught",
    "Overwhelming Hunger",
    "Patricidal Fury",
    "Pincer Maneuver",
    "Pirate's Cove",
    "Precision Strike",
    "Rage of the Sea",
    "Reckless Flurry",
    "Royal Inspiration",
    "Shieldwall",
    "Stockpile",
    "Tactical Decision",
    "Toussaintois Hospitality",
    "Uprising",
    "Ursine Ritual",
    "White Frost",
)
