"""The in-memory, multi-game card store, keyed on nocab_uuid alone.

See src/data_refinement/README.md for this container's scope and
src/data_refinement/card_binder/README.md for the full design this
implements. Design decided in plans/card_binder_v2.md.

CardBinder has no opinion about "sameness" beyond nocab_uuid — it does
NOT enforce any uniqueness invariant over name, alias, or anything
else. Deciding whether a raw row is the same card as one already
stored, and what to do if so, is entirely each CardIngestionStage
implementation's job (see ingestion.py) — CardBinder only ever stores
whatever GenericCard it's handed, keyed by that card's own
nocab_uuid.

A nocab_uuid, once minted for a card, is never regenerated by anything
in this file — a save()/load() round-trip returns the exact same uuid
for the exact same card, always (see load()'s docstring).

CardBinder is a Facade (PATTERNS.md) over the canonical card store
PLUS a privately owned AliasLedger — callers never see AliasLedger
directly, only CardBinder's own get_by_alias()/register_alias().
"""

import json
import re
from dataclasses import replace
from datetime import datetime
from pathlib import Path
from typing import ClassVar, Iterable
from uuid import UUID

from src.data_refinement.card_binder.alias_ledger import AliasLedger
from src.schema.card import GenericCard, Provenance
from src.schema.data_source import DataSource
from src.schema.game_id import GameId


class CardBinder:
    """In-memory, multi-game card store, keyed by nocab_uuid.

    Single-consumer-per-instance is not the right frame here — this is
    the shared, generic storage capability every data_refinement stage
    and training itself reads from (see this container's README).
    Construction is always empty (__init__ takes no
    arguments); load() is the sole populated-construction entry point.
    """

    DEFAULT_OUTPUT_DIR: ClassVar[Path] = Path("data/final/cards")
    DEFAULT_OUTPUT_NAME: ClassVar[str] = "{game}.jsonl"

    def __init__(self) -> None:
        """Construct an empty binder, with an empty owned AliasLedger.

        Prefer load([]) over calling this directly when the intent is
        "start empty for an ingestion run" — this constructor exists
        because load() is itself built on top of it.

        Inputs: none.
        Output: none (constructor).
        Side effects: none.
        Exceptions: none.
        """
        self._cards_by_uuid: dict[UUID, GenericCard] = {}
        self._uuids_by_name: dict[tuple[GameId, str], set[UUID]] = {}
        self._alias_ledger = AliasLedger()

    # region CRUD by UUID

    def create(self, card: GenericCard) -> GenericCard:
        """Insert a brand-new card.

        Callers (CardIngestionStage implementations) are expected to
        have already determined, via this binder's own read methods,
        that card.nocab_uuid represents a genuinely new card — this
        method exists to catch the mistake of calling it twice for the
        same uuid, not to perform that determination itself.

        Inputs:
            card: the card to insert. card.nocab_uuid MUST NOT already
                be stored.
        Output: card, unchanged (returned for symmetry with
            update()/replace(), which do return a possibly-different
            object).
        Side effects: mutates this binder's in-memory indices.
        Exceptions: raises ValueError if card.nocab_uuid is already
            stored — use update() or replace() instead.

        Example:
            >>> binder = CardBinder()
            >>> binder.create(some_card)
        """
        if card.nocab_uuid in self._cards_by_uuid:
            raise ValueError(f"create: {card.nocab_uuid} is already stored")
        self._upsert_card(card)
        return card

    def update(
        self,
        nocab_uuid: UUID,
        raw_content_patch: dict | None = None,
        name: str | None = None,
        provenance: Provenance | None = None,
    ) -> GenericCard:
        """Shallow-merge changes into an already-stored card.

        raw_content_patch is merged one level deep into the existing
        card's raw_content (existing keys overwritten by patch's
        values, keys not present in patch are left untouched, new keys
        in patch are added) — a dict.update(), not a deep merge. name
        and provenance, if given, fully replace the existing card's
        value for that field; if omitted (None), that field is left
        untouched. This is the "dictionary merge" counterpart to
        replace()'s full swap — see this class's docstring and
        plans/card_binder_v2.md for the distinction.

        Inputs:
            nocab_uuid: identity of the card to update. MUST already
                be stored.
            raw_content_patch: fields to shallow-merge into the
                existing card's raw_content. None (default) leaves
                raw_content untouched entirely.
            name: new name, or None (default) to leave unchanged.
            provenance: new provenance, or None (default) to leave
                unchanged.
        Output: the updated GenericCard as now stored.
        Side effects: mutates this binder's in-memory indices.
        Exceptions: raises KeyError if nocab_uuid isn't stored.

        Example:
            >>> binder = CardBinder()
            >>> binder.create(some_card)
            >>> binder.update(some_card.nocab_uuid, raw_content_patch={"hp": "90"})
        """
        if nocab_uuid not in self._cards_by_uuid:
            raise KeyError(f"update: {nocab_uuid} is not stored")
        existing = self._cards_by_uuid[nocab_uuid]

        raw_content = (
            {**existing.raw_content, **raw_content_patch}
            if raw_content_patch is not None
            else existing.raw_content
        )
        updated = replace(
            existing,
            raw_content=raw_content,
            name=name if name is not None else existing.name,
            provenance=provenance if provenance is not None else existing.provenance,
        )
        self._upsert_card(updated)
        return updated

    def replace(self, nocab_uuid: UUID, card: GenericCard) -> GenericCard:
        """Fully overwrite an already-stored card's content.

        Every field of card (raw_content, provenance, name,
        source_game) becomes the stored value for nocab_uuid —
        conceptually a delete-then-add, except nocab_uuid itself never
        changes. This is the "delete then add" counterpart to
        update()'s shallow merge — see this class's docstring.

        Inputs:
            nocab_uuid: identity of the card to replace. MUST already
                be stored.
            card: the new full card content. card.nocab_uuid MUST
                equal nocab_uuid — this method swaps content, it does
                not move a card to a different uuid.
        Output: card, unchanged (returned for symmetry with update()).
        Side effects: mutates this binder's in-memory indices.
        Exceptions: raises KeyError if nocab_uuid isn't stored (use
            create() for a genuinely new uuid). Raises ValueError if
            card.nocab_uuid != nocab_uuid.

        Example:
            >>> binder = CardBinder()
            >>> binder.create(some_card)
            >>> merged = merge_strategies.keep_incoming(some_card, other_card)
            >>> binder.replace(some_card.nocab_uuid, merged)
        """
        if card.nocab_uuid != nocab_uuid:
            raise ValueError(
                f"replace: card.nocab_uuid ({card.nocab_uuid}) != target uuid ({nocab_uuid})"
            )
        if nocab_uuid not in self._cards_by_uuid:
            raise KeyError(f"replace: {nocab_uuid} is not stored")
        self._upsert_card(card)
        return card

    def delete(self, nocab_uuid: UUID) -> None:
        """Remove a card entirely.

        New capability — no equivalent exists in the pre-card_binder_v2
        design. Useful for a source that drops a card on re-fetch
        (e.g. a banned/rotated card, a removed printing).

        Inputs:
            nocab_uuid: identity of the card to remove. MUST already
                be stored.
        Output: none.
        Side effects: mutates this binder's in-memory indices. Does
            NOT remove any AliasLedger entries pointing at nocab_uuid
            — those become dangling (resolve to a uuid get_by_uuid()
            no longer returns a card for). Acceptable for now; revisit
            if a real caller needs alias cleanup on delete.
        Exceptions: raises KeyError if nocab_uuid isn't stored.

        Example:
            >>> binder = CardBinder()
            >>> binder.create(some_card)
            >>> binder.delete(some_card.nocab_uuid)
        """
        if nocab_uuid not in self._cards_by_uuid:
            raise KeyError(f"delete: {nocab_uuid} is not stored")

        card = self._cards_by_uuid.pop(nocab_uuid)
        name_key = (card.source_game, card.name)
        self._uuids_by_name[name_key].discard(nocab_uuid)
        if not self._uuids_by_name[name_key]:
            del self._uuids_by_name[name_key]

    # endregion CRUD by UUID

    # region Card Getters

    def get_by_uuid(self, nocab_uuid: UUID) -> GenericCard | None:
        """Look up a card by this system's own identity.

        Inputs:
            nocab_uuid: identity to look up.
        Output: the matching GenericCard, or None if no card has this
            nocab_uuid.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> binder = CardBinder.load([Path("data/final/cards/mtg.jsonl")])
            >>> binder.get_by_uuid(some_uuid)
        """
        return self._cards_by_uuid.get(nocab_uuid)

    def get_by_name(self, source_game: GameId, name: str) -> list[GenericCard]:
        """Look up every card with a given name.

        BREAKING CHANGE from the pre-card_binder_v2 design: name is no
        longer assumed unique within a game (e.g. Slay the Spire 2 has
        5 cards named "Strike", Pokemon has same-named reprints with
        different rules text) — see plans/card_binder_v2.md's "Why".

        Inputs:
            source_game: which game's name namespace to look in.
            name: card name to look up.
        Output: every GenericCard registered under this
            (source_game, name), in no particular guaranteed order.
            Empty list if none match.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> binder = CardBinder.load([Path("data/final/cards/slay_the_spire_2.jsonl")])
            >>> binder.get_by_name(GameId.SLAY_THE_SPIRE_2, "Strike")
        """
        uuids = self._uuids_by_name.get((source_game, name), set())
        return [self._cards_by_uuid[nocab_uuid] for nocab_uuid in uuids]

    def get_by_name_single(
        self, source_game: GameId, name: str, strict: bool = True
    ) -> GenericCard | None:
        """Look up one card by name, for callers that expect at most one.

        Convenience over get_by_name() for games where the calling
        code knows (or is willing to assume) names are unique — e.g.
        MTG's 17lands pipelines, Dojo.prepare_splits.

        Inputs:
            source_game: which game's name namespace to look in.
            name: card name to look up.
            strict: if True (default), more than one match raises —
                use this when the caller's assumption of uniqueness
                should be verified, not silently papered over. If
                False, one of the matches is returned (which one is
                unspecified) — use this only when the caller has
                already accepted that ambiguity is possible and just
                wants *a* plausible card.
        Output: the matching GenericCard, or None if no card matches
            this (source_game, name).
        Side effects: none.
        Exceptions: raises ValueError if strict=True and more than one
            card matches.

        Example:
            >>> binder = CardBinder.load([Path("data/final/cards/mtg.jsonl")])
            >>> binder.get_by_name_single(GameId.MTG, "Lightning Bolt")
        """
        matches = self.get_by_name(source_game, name)
        if not matches:
            return None
        if len(matches) > 1 and strict:
            raise ValueError(
                f"get_by_name_single: {len(matches)} cards match "
                f"({source_game!r}, {name!r}) — ambiguous under strict=True"
            )
        return matches[0]

    def get_by_name_regex(self, source_game: GameId, pattern: str) -> list[GenericCard]:
        """Look up every card whose name matches a regex pattern.

        Generic, source-agnostic search — ported unchanged from the
        pre-card_binder_v2 design. See
        src/data_refinement/seventeenlands/game_data_metrics/ and
        draft_data_metrics/ for the 17lands-specific fallback logic
        that calls this — NOT this method's concern.

        Inputs:
            source_game: which game's cards to search.
            pattern: a regular expression, matched against each
                candidate card's name via re.match(pattern, name).
        Output: every GenericCard in source_game whose name matches
            pattern, in no particular guaranteed order.
        Side effects: none.
        Exceptions: raises re.error if pattern is not a valid regular
            expression.

        Example:
            >>> binder = CardBinder.load([Path("data/final/cards/mtg.jsonl")])
            >>> binder.get_by_name_regex(GameId.MTG, r"^Bruce Banner( //.*)?$")
        """
        return [
            card
            for card in self._cards_by_uuid.values()
            if card.source_game == source_game and re.match(pattern, card.name)
        ]

    def get_by_alias(
        self, source_game: GameId, data_source: DataSource, source_id: str
    ) -> GenericCard | None:
        """Look up a card by an external system's identifier for it.

        Resolves through the internal AliasLedger, then get_by_uuid().

        Inputs:
            source_game: which game's namespace to look in.
            data_source: which external system minted source_id (e.g.
                DataSource.SCRYFALL, DataSource.ARENA).
            source_id: that system's own id (e.g. a Scryfall oracle_id
                or Arena numeric card id).
        Output: the matching GenericCard, or None if no card is
            registered under this (source_game, data_source, source_id).
        Side effects: none.
        Exceptions: none.

        Example:
            >>> binder = CardBinder.load([Path("data/final/cards/mtg.jsonl")])
            >>> binder.get_by_alias(GameId.MTG, DataSource.ARENA, "76497")
        """
        nocab_uuid = self._alias_ledger.resolve(source_game, data_source, source_id)
        if nocab_uuid is None:
            return None
        return self.get_by_uuid(nocab_uuid)

    def all_uuids(self, source_game: GameId | None = None) -> Iterable[UUID]:
        """Every nocab_uuid currently stored in this binder.

        Inputs:
            source_game: if given, only uuids for cards in this game
                are returned. None (default) returns every uuid this
                binder holds, across every game it has loaded.
        Output: every matching nocab_uuid, in no particular guaranteed
            order.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> binder = CardBinder.load([Path("data/final/cards/mtg.jsonl")])
            >>> list(binder.all_uuids())
            >>> list(binder.all_uuids(GameId.MTG))
        """
        if source_game is None:
            return self._cards_by_uuid.keys()
        return [
            nocab_uuid
            for nocab_uuid, card in self._cards_by_uuid.items()
            if card.source_game == source_game
        ]

    def all_cards(self, source_game: GameId) -> Iterable[GenericCard]:
        """Every card currently stored in this binder for one game.

        New — direct enumeration. Previously required all_uuids()
        followed by one get_by_uuid() call per id.

        Inputs:
            source_game: which game's cards to enumerate.
        Output: every GenericCard in source_game, in no particular
            guaranteed order.
        Side effects: none.
        Exceptions: none.

        Example:
            >>> binder = CardBinder.load([Path("data/final/cards/mtg.jsonl")])
            >>> list(binder.all_cards(GameId.MTG))
        """
        return [
            card for card in self._cards_by_uuid.values() if card.source_game == source_game
        ]

    # endregion Card Getters

    # region Persistence

    def register_alias(
        self,
        source_game: GameId,
        data_source: DataSource,
        source_id: str,
        nocab_uuid: UUID,
    ) -> None:
        """Register one external identifier against an already-stored card.

        Called directly by whichever CardIngestionStage implementation
        is processing a row — under the card_binder_v2 design, a stage
        owns its own collision handling and is responsible for calling
        this itself (for both a row's own primary identifier and any
        secondary ones a source carries) on every branch of that
        handling, not just the branches that change stored content.
        See plans/card_binder_v2.md's "Open risks" for why this isn't
        centrally enforced.

        Inputs:
            source_game: which game's namespace this identifier
                belongs to.
            data_source: which external system minted source_id.
            source_id: that system's own id.
            nocab_uuid: the nocab_uuid this identifier should resolve
                to — MUST already be a card this binder holds.
        Output: none.
        Side effects: mutates this binder's owned AliasLedger.
        Exceptions: raises ValueError if nocab_uuid isn't a card this
            binder currently holds — an AliasLedger entry pointing at
            a phantom uuid would be a silent data-integrity bug.

        Example:
            >>> binder = CardBinder()
            >>> binder.create(some_card)
            >>> binder.register_alias(GameId.MTG, DataSource.ARENA, "76497", some_card.nocab_uuid)
        """
        if nocab_uuid not in self._cards_by_uuid:
            raise ValueError(f"register_alias: {nocab_uuid} is not a card this binder holds")
        self._alias_ledger.register(source_game, data_source, source_id, nocab_uuid)

    @staticmethod
    def load(paths: list[Path]) -> "CardBinder":
        """Load and merge one or more per-game JSONL files into one binder.

        Every row's nocab_uuid, as written by whatever save() produced
        that row, is reinserted UNCHANGED — no remapping of any kind
        happens here (unlike the pre-card_binder_v2 design, which had
        to remap uuids on cross-file name collisions; that concern
        doesn't exist once uniqueness is uuid-only). If the same
        nocab_uuid legitimately appears in more than one loaded path,
        last-path-wins (a plain overwrite) — paths are processed in
        the given order, with no merge/richness logic, since collision
        resolution isn't CardBinder's job anywhere in this design.

        REQUIRED test coverage per plans/card_binder_v2.md: a
        save() -> load() round trip must be verified to return a
        card whose nocab_uuid is bit-for-bit identical to what was
        saved.

        load([]) — an empty list — is the sanctioned way to start a
        fresh, empty binder.

        Inputs:
            paths: zero or more paths to data/final/cards/<game>.jsonl-
                shaped files. Files for different games can be mixed
                in one call.
        Output: a populated CardBinder containing every card from
            every given path (last-path-wins on a uuid appearing more
            than once), with every alias (if any sibling
            alias_ledger files are present) also resolvable.
        Side effects: reads each path in paths, and each one's sibling
            alias_ledger file if present.
        Exceptions: raises if any path in paths doesn't exist or
            contains a line that doesn't deserialize to a valid
            GenericCard.

        Example:
            >>> binder = CardBinder.load([Path("data/final/cards/mtg.jsonl")])
            >>> empty_binder = CardBinder.load([])
        """
        binder = CardBinder()
        for path in paths:
            with open(path, "r", encoding="utf-8") as binder_file:
                for line in binder_file:
                    row = json.loads(line)
                    card = GenericCard(
                        nocab_uuid=UUID(row["nocab_uuid"]),
                        source_game=GameId(row["source_game"]),
                        name=row["name"],
                        raw_content=row["raw_content"],
                        provenance=Provenance(
                            data_source=DataSource(row["provenance"]["data_source"]),
                            source_id=row["provenance"]["source_id"],
                            fetched_at=datetime.fromisoformat(row["provenance"]["fetched_at"]),
                        ),
                    )
                    binder._upsert_card(card)

            alias_ledger_path = CardBinder._alias_ledger_path(path)
            if alias_ledger_path.exists():
                with open(alias_ledger_path, "r", encoding="utf-8") as ledger_file:
                    for line in ledger_file:
                        alias_row = json.loads(line)
                        nocab_uuid = UUID(alias_row["nocab_uuid"])
                        aliased_card = binder.get_by_uuid(nocab_uuid)
                        if aliased_card is None:
                            continue
                        binder.register_alias(
                            aliased_card.source_game,
                            DataSource(alias_row["data_source"]),
                            alias_row["source_id"],
                            nocab_uuid,
                        )
        return binder

    @staticmethod
    def default_output_path(source_game: GameId) -> Path:
        """The conventional save() path for one game's binder file.

        A recommended default, not an enforced requirement — callers
        remain free to save() to any path; this exists so a caller
        (e.g. a Dojo defaulting its own metrics_path/binder location)
        can compute the same conventional path this project already
        uses elsewhere, instead of re-typing the string.

        Inputs:
            source_game: which game's conventional path to compute.
        Output: DEFAULT_OUTPUT_DIR / DEFAULT_OUTPUT_NAME, formatted
            with source_game (e.g. data/final/cards/mtg.jsonl).
        Side effects: none — purely a path computation.
        Exceptions: none.

        Example:
            >>> CardBinder.default_output_path(GameId.MTG)
            PosixPath('data/final/cards/mtg.jsonl')
        """
        return CardBinder.DEFAULT_OUTPUT_DIR / CardBinder.DEFAULT_OUTPUT_NAME.format(
            game=source_game.value
        )

    def save(self, path: Path, source_game: GameId) -> None:
        """Write this binder's cards for one game to path, as JSONL.

        Only cards with card.source_game == source_game are written.
        Writes the main file, then delegates to
        self._alias_ledger.save(...) for the sibling
        <game>.alias_ledger.jsonl file — CardBinder never writes alias
        entries itself; AliasLedger owns its own file format.

        REQUIRED test coverage per plans/card_binder_v2.md: pair with
        load() in a round-trip test asserting nocab_uuid survives
        unchanged — see load()'s docstring.

        Inputs:
            path: destination file (e.g.
                data/final/cards/<game>.jsonl). Overwritten if it
                already exists.
            source_game: which game's subset of this binder to write.
        Output: none.
        Side effects: creates path's parent directory if missing;
            writes/overwrites path and its sibling alias_ledger file.
        Exceptions: raises on failure to write either file.

        Example:
            >>> binder.save(Path("data/final/cards/mtg.jsonl"), GameId.MTG)
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as binder_file:
            for card in self._cards_by_uuid.values():
                if card.source_game != source_game:
                    continue
                row = {
                    "nocab_uuid": str(card.nocab_uuid),
                    "source_game": card.source_game.value,
                    "name": card.name,
                    "raw_content": card.raw_content,
                    "provenance": {
                        "data_source": card.provenance.data_source.value,
                        "source_id": card.provenance.source_id,
                        "fetched_at": card.provenance.fetched_at.isoformat(),
                    },
                }
                binder_file.write(json.dumps(row) + "\n")

        self._alias_ledger.save(self._alias_ledger_path(path), source_game)

    # endregion Persistence

    # region Private Helpers

    def _upsert_card(self, card: GenericCard) -> None:
        """Insert or overwrite card in this binder's indices.

        Private helper — shared by create()/update()/replace()/load(),
        the only places that ever need to actually mutate storage.
        None of them enforce any invariant here (that's each public
        method's own job before calling this) — this method just
        stores whatever it's given.

        Must correctly handle the case where card.nocab_uuid was
        ALREADY stored under a different (source_game, name) tuple —
        an update()/replace() call that changes name, OR a replace()
        call that changes source_game (replace()'s contract allows
        swapping every field, source_game included): the stale
        (old_source_game, old_name) entry in _uuids_by_name has to be
        removed, not just a new entry added under the new tuple, or
        get_by_name() would keep returning this card under a
        (game, name) pair it no longer belongs to.

        Inputs:
            card: the card to store as canonical for its nocab_uuid.
        Output: none.
        Side effects: mutates this binder's uuid and name indices.
        Exceptions: none.
        """
        old_card = self._cards_by_uuid.get(card.nocab_uuid)
        old_name_key = (old_card.source_game, old_card.name) if old_card is not None else None
        new_name_key = (card.source_game, card.name)

        self._cards_by_uuid[card.nocab_uuid] = card

        if old_name_key is not None and old_name_key != new_name_key:
            self._uuids_by_name[old_name_key].discard(card.nocab_uuid)
            if not self._uuids_by_name[old_name_key]:
                del self._uuids_by_name[old_name_key]

        self._uuids_by_name.setdefault(new_name_key, set()).add(card.nocab_uuid)

    @staticmethod
    def _alias_ledger_path(path: Path) -> Path:
        """Compute the sibling alias-ledger path for a main binder path.

        Private helper — shared by load() and save(). E.g.
        data/final/cards/mtg.jsonl -> data/final/cards/mtg.alias_ledger.jsonl.

        Inputs:
            path: a main binder file path (e.g.
                data/final/cards/mtg.jsonl).
        Output: the corresponding alias-ledger file path.
        Side effects: none — purely a path computation.
        Exceptions: none.
        """
        return path.with_suffix(".alias_ledger" + path.suffix)

    # endregion Private Helpers
